Repository Shopify/ruby-lsp, pull requests merged in 2022-07, with the labels that each got.

#222 Prevent breaking on nameless keyword rest parameters
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/fixtures/nameless_keyword_rest.rb
Labels: bug

#221 Centralize request handling logic in server.rb
  exe/ruby-lsp
  lib/ruby_lsp/cli.rb
  lib/ruby_lsp/handler.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/server.rb
Labels: LSP

#223 Fix FCall within chained invocation in folding ranges
  lib/ruby_lsp/requests/folding_ranges.rb
  test/expectations/folding_ranges/fcall_chained_invocation.exp
  test/fixtures/fcall_chained_invocation.rb
Labels: bug

#228 Avoid trying to access name if the rest parameter is an ArgsForward
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/fixtures/argument_forwarding.rb
Labels: bug

#195 Support DocumentLink request
  lib/ruby_lsp/requests.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/server.rb
  misc/document_link.gif
  sorbet/rbi/shims/expectations_test_runner.rbi
  test/expectations/document_link/source_comment.exp
  test/fixtures/source_comment.rb
  test/integration_test.rb
  test/requests/document_link_expectations_test.rb
Labels: enhancement

#232 Avoid returning from on request blocks
  lib/ruby_lsp/server.rb
  test/integration_test.rb
Labels: bug
