Repository Shopify/ruby-lsp, pull requests merged in 2022-08, with the labels that each got.

#236 Fix call processing when message is a :call symbol literal
  lib/ruby_lsp/requests/semantic_highlighting.rb
  lib/ruby_lsp/requests/support/highlight_target.rb
  test/expectations/semantic_highlighting/call_symbol_call.exp
  test/fixtures/call_symbol_call.rb
  test/fixtures/hash_safe_access.rb
Labels: bug

#243 Add request cancellation
  lib/ruby_lsp/handler.rb
  lib/ruby_lsp/queue.rb
  lib/ruby_lsp/server.rb
  test/handler_test.rb
  test/queue_test.rb
Labels: unstable

#269 Add runtime dependency on version 3.17.x of LSP gem
  Gemfile.lock
  ruby-lsp.gemspec
Labels: chore
