Repository Shopify/ruby-lsp, pull requests merged in 2022-10, with the labels that each got.

#318 Add release.yml
  .github/release.yml
Labels: chore

#332 Use newer checkout action
  .github/workflows/ci.yml
  .github/workflows/release.yml
Labels: chore

#284 Add semantic tokens for local arguments
  Gemfile.lock
  lib/ruby_lsp/requests/semantic_highlighting.rb
  ruby-lsp.gemspec
  sorbet/rbi/gems/nokogiri@1.13.9.rbi
  sorbet/rbi/gems/prettier_print@1.0.2.rbi
  sorbet/rbi/gems/syntax_tree@4.0.2.rbi
  sorbet/rbi/shims/syntax_tree.rbi
  test/expectations/semantic_highlighting/lambdas.exp
  test/expectations/semantic_highlighting/local_vars_and_params.exp
  test/expectations/semantic_highlighting/method_params.exp
  test/expectations/semantic_highlighting/shadowed_block_arg.exp
  test/expectations/semantic_highlighting/single_line_lambda.exp
  test/fixtures/local_vars_and_params.rb
  test/fixtures/shadowed_block_arg.rb
Labels: enhancement

#339 Handle fields in semantic highlighting
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/expectations/semantic_highlighting/field_assignment.exp
  test/fixtures/field_assignment.rb
Labels: bug
