Repository Shopify/ruby-lsp, pull requests merged in 2023-11, with the labels that each got.

#1171 Use a queue instead of visitor for indexing
  exe/ruby-lsp-doctor
  lib/ruby_indexer/lib/ruby_indexer/collector.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix

#1194 Keep track of method owners and add resolve_method
  lib/ruby_indexer/lib/ruby_indexer/collector.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_indexer/test/method_test.rb
Labels: enhancement

#1196 Return server information on initalize request
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/requests/support/dependency_detector.rb
  test/executor_test.rb
Labels: bugfix

#1195 Support methods invoked on self
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  lib/ruby_lsp/utils.rb
  sorbet/config
  test/requests/completion_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/workspace_symbol_test.rb
Labels: enhancement

#1203 Disregard quotes in string node location for require path completion
  lib/ruby_lsp/requests/completion.rb
  test/requests/completion_test.rb
Labels: bugfix

#1215 Remove comment continuation anchor
  lib/ruby_lsp/requests/on_type_formatting.rb
  test/requests/on_type_formatting_test.rb
Labels: bugfix

#1214 Make test CodeLens request aware of test hierarchy
  lib/ruby_lsp/requests/code_lens.rb
  test/expectations/code_lens/minitest_tests.exp.json
  test/expectations/code_lens/nested_minitest_tests.exp.json
Labels: enhancement

#1221 Avoid indexing non-Ruby files added inside rubylibdir
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/test/configuration_test.rb
Labels: bugfix

#1224 Keep track of optional parameters
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/test/method_test.rb
Labels: enhancement

#1225 Verify indexing on `ruby-lsp-check` and against Prism fixtures
  exe/ruby-lsp-check
  lib/ruby_indexer/test/index_test.rb
Labels: chore

#1223 Move ownership of message_queue from listeners to addon
  ADDONS.md
  exe/ruby-lsp-check
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/listener.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/requests/document_symbol.rb
  lib/ruby_lsp/requests/folding_ranges.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/inlay_hints.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/addon_test.rb
  test/expectations/expectations_test_runner.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/document_highlight_expectations_test.rb
  test/requests/document_link_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/folding_ranges_expectations_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/inlay_hints_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
Labels: breaking-change
