Repository Shopify/ruby-lsp, pull requests merged in 2023-06, with the labels that each got.

#694 Add --help to ruby-lsp command, and detect invalid arguments
  exe/ruby-lsp
Labels: enhancement

#737 Always append test class name to the test command
  lib/ruby_lsp/requests/code_lens.rb
  test/expectations/code_lens/minitest_tests.exp.json
  test/expectations/code_lens/nested_minitest_tests.exp.json
Labels: bugfix

#747 Ensure CI runs on Windows
  .github/workflows/ci.yml
  test/integration_test.rb
  test/requests/diagnostics_expectations_test.rb
Labels: chore

#746 Distinguish test-unit and minitest in code lens
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/support/dependency_detector.rb
  test/requests/code_lens_expectations_test.rb
Labels: bugfix

#764 Prevent breaking on empty gem statements
  lib/ruby_lsp/requests/code_lens.rb
  test/fixtures/Gemfile.rb
Labels: bugfix

#765 Skip test code lens on methods unless its inside a test class
  lib/ruby_lsp/requests/code_lens.rb
  test/fixtures/minitest_tests.rb
Labels: bugfix

#767 Add screen capture details
  CONTRIBUTING.md
Labels: chore

#773 Don't use Minitest for running tests in a Rails app
  lib/ruby_lsp/requests/support/dependency_detector.rb
  test/requests/support/dependency_detector_test.rb
Labels: enhancement

#774 Catch LoadError exceptions from formatting calls
  lib/ruby_lsp/executor.rb
Labels: bugfix

#771 Add server extensions documentation
  README.md
  SERVER_EXTENSIONS.md
Labels: documentation

#786 Use empty? instead of blank? on strings
  lib/ruby_lsp/requests/on_type_formatting.rb
Labels: bugfix

#789 Create and synchronize custom bundle in the server
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: breaking-change
