Repository Shopify/ruby-lsp, pull requests merged in 2023-10, with the labels that each got.

#1054 Follow-ups for DependencyDetector refactoring
  test/requests/support/dependency_detector_test.rb
  test/requests/workspace_symbol_test.rb
Labels: chore

#1038 Handle namespace aliases in completion
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_lsp/requests/completion.rb
  test/requests/completion_test.rb
Labels: enhancement

#1065 Unset deployment mode on version bump automation
  .github/workflows/version_bump.yml
Labels: chore

#1049 Index ConstantAndWrite and ConstantOperatorWrite
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/test/constant_test.rb
Labels: bugfix

#1084 Show indexing percentage on progress notifications
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_lsp/executor.rb
  test/executor_test.rb
  test/integration_test.rb
Labels: enhancement

#1034 Index constant targets
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/test/constant_test.rb
Labels: enhancement

#1093 Respect local bundler configuration
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix

#1085 Remove node override selection ranges
  lib/ruby_lsp/requests/selection_ranges.rb
  test/expectations/selection_ranges/array_literal_oneline.exp.json
  test/expectations/selection_ranges/begin_rescue_ensure.exp.json
  test/expectations/selection_ranges/case_when.exp.json
  test/expectations/selection_ranges/class_declaration.exp.json
  test/expectations/selection_ranges/class_declaration_nested.exp.json
  test/expectations/selection_ranges/def.exp.json
  test/expectations/selection_ranges/def_endless.exp.json
  test/expectations/selection_ranges/def_multiline_params.exp.json
  test/expectations/selection_ranges/def_oneline.exp.json
  test/expectations/selection_ranges/def_require_name_parameter.exp.json
  test/expectations/selection_ranges/defs.exp.json
  test/expectations/selection_ranges/defs_multiline_params.exp.json
  test/expectations/selection_ranges/do_blocks.exp.json
  test/expectations/selection_ranges/ensure.exp.json
  test/expectations/selection_ranges/for.exp.json
  test/expectations/selection_ranges/hash_literal.exp.json
  test/expectations/selection_ranges/hash_literal_oneline.exp.json
  test/expectations/selection_ranges/heredoc.exp.json
  test/expectations/selection_ranges/if.exp.json
  test/expectations/selection_ranges/if_elsif_else.exp.json
  test/expectations/selection_ranges/if_elsif_else_empty.exp.json
  test/expectations/selection_ranges/lambdas.exp.json
  test/expectations/selection_ranges/module_declaration.exp.json
  test/expectations/selection_ranges/multiline_arrays.exp.json
  test/expectations/selection_ranges/multiline_block.exp.json
  test/expectations/selection_ranges/multiline_invocation.exp.json
  test/expectations/selection_ranges/nested_invocation.exp.json
  test/expectations/selection_ranges/nested_invocation_no_parenthesis.exp.json
  test/expectations/selection_ranges/pattern_matching.exp.json
  test/expectations/selection_ranges/rescue_multiple.exp.json
  test/expectations/selection_ranges/sclass.exp.json
  test/expectations/selection_ranges/string_concat.exp.json
  test/expectations/selection_ranges/unless.exp.json
  test/expectations/selection_ranges/until.exp.json
  test/expectations/selection_ranges/while.exp.json
  test/integration_test.rb
Labels: bugfix

#1097 Switch to Prism::Dispatcher
  ADDONS.md
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/event_emitter.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/listener.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/requests/document_symbol.rb
  lib/ruby_lsp/requests/folding_ranges.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/inlay_hints.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/expectations/definition/requires.exp.json
  test/expectations/expectations_test_runner.rb
  test/fixtures/requires.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/document_highlight_expectations_test.rb
  test/requests/document_link_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/folding_ranges_expectations_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/inlay_hints_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
Labels: breaking-change

#1109 Ignore default gems that are missing in the current platform
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
Labels: bugfix

#1112 Extract Entry from Indexer
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/constant_test.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_indexer/test/method_test.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
Labels: refactoring

#1107 Reduce `Completion#top_level?` complexity
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_lsp/requests/completion.rb
  test/requests/completion_test.rb
Labels: bugfix

#1117 Add `ruby-lsp-doctor` tool for troubleshooting indexing problems
  .github/workflows/ci.yml
  exe/ruby-lsp-doctor
  ruby-lsp.gemspec
Labels: enhancement

#1126 Make the experimental flag install beta versions of the server
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: enhancement

#1159 Skip exclusion logic if `to_spec` returns `nil`
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
Labels: bugfix

#1153 Improve document symbols of singleton class operators and methods
  lib/ruby_lsp/requests/document_symbol.rb
  test/expectations/document_symbol/defs.exp.json
  test/expectations/document_symbol/sclass_operator.exp.json
  test/fixtures/sclass_operator.rb
Labels: bugfix
