Repository Shopify/ruby-lsp, pull requests merged in 2023-01, with the labels that each got.

#412 Reduce noise in test output
  .rubocop.yml
  README.md
  lib/ruby_lsp/handler.rb
  lib/ruby_lsp/requests/support/rails_document_client.rb
  test/test_helper.rb
Labels: chore

#411 Fix comment continuation incorrectly matching keywords
  lib/ruby_lsp/requests/on_type_formatting.rb
  test/requests/on_type_formatting_test.rb
Labels: bug

#451 Refactor locating nodes based on positions
  lib/ruby_lsp/requests/base_request.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/hover.rb
  test/expectations/hover/model_active_record_constant.exp.json
  test/requests/base_request_test.rb
Labels: bug

#368 Completely dettach IO from parallel request execution
  bin/console
  exe/ruby-lsp
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/handler.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/queue.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/utils.rb
  test/integration_test.rb
  test/queue_test.rb
Labels: enhancement, breaking-change

#447 Add overview
  README.md
Labels: documentation
