Repository Shopify/ruby-lsp, pull requests merged in 2023-08, with the labels that each got.

#837 Prevent dependency detector from failing outside of a bundle
  lib/ruby_lsp/requests/support/dependency_detector.rb
  test/requests/support/dependency_detector_test.rb
Labels: bugfix

#849 Test against Ruby head and use 3.2.2
  .github/workflows/ci.yml
  dev.yml
Labels: chore

#847 Use pathnames and bundler methods in custom bundle logic
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix

#829 Refactor listener registration
  SERVER_EXTENSIONS.md
  lib/ruby_lsp/extension.rb
  lib/ruby_lsp/listener.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/server.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/hover_expectations_test.rb
Labels: breaking-change

#848 Use URI objects instead of strings
  bin/benchmark
  exe/ruby-lsp-check
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/extension.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/requests/code_actions.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/diagnostics.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/requests/formatting.rb
  lib/ruby_lsp/requests/support/formatter_runner.rb
  lib/ruby_lsp/requests/support/rubocop_diagnostic.rb
  lib/ruby_lsp/requests/support/rubocop_diagnostics_runner.rb
  lib/ruby_lsp/requests/support/rubocop_formatting_runner.rb
  lib/ruby_lsp/requests/support/syntax_tree_formatting_runner.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/store.rb
  test/document_test.rb
  test/executor_test.rb
  test/expectations/expectations_test_runner.rb
  test/requests/code_action_resolve_expectations_test.rb
  test/requests/code_actions_expectations_test.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/diagnostics_test.rb
  test/requests/document_highlight_expectations_test.rb
  test/requests/document_link_expectations_test.rb
  test/requests/formatting_expectations_test.rb
  test/requests/formatting_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/inlay_hints_expectations_test.rb
  test/requests/on_type_formatting_test.rb
  test/requests/path_completion_test.rb
  test/requests/selection_ranges_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
  test/requests/show_syntax_tree_test.rb
  test/store_test.rb
Labels: breaking-change

#857 Use hash to compare lockfiles instead of modified timestamps
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix

#858 Add .irbrc to customise IRB for the project
  .irbrc
  bin/console
Labels: chore

#874 Add indexer
  .rubocop.yml
  Gemfile.lock
  Rakefile
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_lsp/internal.rb
  ruby-lsp.gemspec
  sorbet/rbi/gems/yarp@0.6.0.rbi
  sorbet/tapioca/require.rb
Labels: enhancement

#885 Account for lowercase drive letter on Windows
  lib/core_ext/uri.rb
  test/requests/support/uri_test.rb
Labels: bugfix

#890 Use the absolute BUNDLE_PATH to run the server
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix

#875 Perform initial indexing and synchronization
  .index.yml
  Gemfile
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/store.rb
  test/executor_test.rb
  test/integration_test.rb
Labels: enhancement

#893 Index constants
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/constant_test.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_indexer/test/test_case.rb
Labels: enhancement

#891 Always use complete URI for store key
  lib/core_ext/uri.rb
  lib/ruby_lsp/store.rb
  test/store_test.rb
Labels: bugfix

#901 Avoid dependency on T::Class and newer Sorbet versions
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
Labels: bugfix

#907 Add workspace symbol
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/requests.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/support/dependency_detector.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  misc/workspace_symbol.gif
  test/integration_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/workspace_symbol_test.rb
Labels: enhancement

#914 Ignore magic comments and prejoin comments
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_indexer/test/constant_test.rb
Labels: enhancement

#919 Fix test file exclusion glob pattern
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/test/configuration_test.rb
Labels: bugfix

#926 Unescape URIs using `DEFAULT_PARSER.unescape` instead of CGI
  lib/core_ext/uri.rb
  test/requests/support/uri_test.rb
Labels: bugfix

#925 Allow definition and workspace symbol to return default gem symbols
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  test/requests/definition_expectations_test.rb
  test/requests/workspace_symbol_test.rb
Labels: bugfix

#929 Push hover separator before extension results
  lib/ruby_lsp/requests/hover.rb
  test/requests/hover_expectations_test.rb
Labels: bugfix

#933 Use bundle check and only update every 4 hours
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: enhancement

#931 Recover from indexing errors
  lib/ruby_lsp/executor.rb
  test/executor_test.rb
Labels: bugfix

#930 Only index gem require paths
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix

#942 Prevent bundle check from printing to stdout
  Gemfile.lock
  VERSION
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix

#946 Make indexing a stable feature
  lib/ruby_lsp/executor.rb
  test/executor_test.rb
  test/integration_test.rb
  test/requests/definition_expectations_test.rb
Labels: enhancement

#958 Use parse! for OptionParser
  exe/ruby-lsp
Labels: bugfix
