Repository Shopify/ruby-lsp, pull requests merged in 2023-05, with the labels that each got.

#672 Remove unnecessary `let`
  lib/ruby_lsp/requests/path_completion.rb
Labels: chore

#660 Migrate document link to listener
  lib/ruby_lsp/event_emitter.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/listener.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/requests/document_symbol.rb
  lib/ruby_lsp/requests/hover.rb
  test/expectations/expectations_test_runner.rb
  test/requests/document_link_expectations_test.rb
Labels: enhancement

#667 Fix check for RuboCop availability
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/requests/support/rubocop_diagnostics_runner.rb
  lib/ruby_lsp/requests/support/rubocop_formatting_runner.rb
Labels: bug

#682 Move `create_code_lens` to `Support::Common`
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/support/common.rb
Labels: chore

#674 Fix check for RuboCop availability (add test)
  test/executor_test.rb
Labels: chore

#701 Add semantic highlighting documentation
  README.md
  SEMANTIC_HIGHLIGHTING.md
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/expectations/semantic_highlighting/module_and_reference.exp.json
Labels: documentation, bugfix

#712 Include test library type in Code Lens
  lib/ruby_lsp/requests/support/common.rb
  test/expectations/code_lens/minitest_tests.exp.json
Labels: chore

#716 Fix Remove duplicate backticks
  lib/ruby_lsp/requests/formatting.rb
Labels: documentation

#710 Add gem actions in the Gemfile
  lib/ruby_lsp/requests/code_lens.rb
  test/expectations/code_lens/Gemfile.exp.json
  test/expectations/code_lens/minitest_tests.exp.json
  test/fixtures/Gemfile.rb
  test/requests/code_lens_expectations_test.rb
Labels: enhancement

#732 Drop Ruby 2.7 support
  .github/workflows/ci.yml
  .rubocop.yml
  lib/ruby_lsp/requests/base_request.rb
  lib/ruby_lsp/utils.rb
  ruby-lsp.gemspec
Labels: breaking-change
