Repository Shopify/ruby-lsp, pull requests merged in 2023-07, with the labels that each got.

#797 Prevent exception on shutdown (Ignore `$/setTrace` requests)
  lib/ruby_lsp/server.rb
Labels: bugfix

#798 Remove empty base request test
  test/requests/base_request_test.rb
Labels: chore

#800 Fix nesting when a target class is specified
  lib/ruby_lsp/document.rb
  test/document_test.rb
Labels: bugfix

#811 Add ruby-lsp-check executable
  .github/workflows/lsp_check.yml
  dev.yml
  exe/ruby-lsp-check
  ruby-lsp.gemspec
Labels: enhancement

#796 Indicate that using `bundle exec` is no longer recommended as of v0.7.0
  EDITORS.md
  README.md
Labels: chore

#825 Update Slack link
  README.md
  SERVER_EXTENSIONS.md
Labels: chore

#836 Avoid mutating nodes in full_constant_name
  lib/ruby_lsp/requests/support/common.rb
Labels: bugfix

#841 Pass environment as a hash to system or exec calls
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix
