Repository Shopify/ruby-lsp, pull requests merged in 2023-09, with the labels that each got.

#959 Filter Sorbet in backtrace
  test/test_helper.rb
Labels: chore

#955 Add entries prefix tree
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/prefix_tree.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_indexer/test/prefix_tree_test.rb
Labels: enhancement

#974 Correct create_document_symbol_listener's signature
  lib/ruby_lsp/extension.rb
Labels: bugfix

#975 Use indexed paths to provide jump to require definition
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/path_completion.rb
  test/expectations/definition/requires.exp.json
  test/fixtures/requires.rb
  test/integration_test.rb
  test/requests/definition_expectations_test.rb
Labels: enhancement

#972 Make requests easier to extend
  SERVER_EXTENSIONS.md
  lib/ruby_lsp/check_docs.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/listener.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/requests/document_symbol.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/inlay_hints.rb
  lib/ruby_lsp/requests/path_completion.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/hover_expectations_test.rb
Labels: breaking-change

#989 Make Definition extensible
  lib/ruby_lsp/extension.rb
  lib/ruby_lsp/requests/definition.rb
  test/requests/definition_expectations_test.rb
Labels: enhancement

#995 Automatically bump version after release
  .github/workflows/version_bump.yml
Labels: chore

#997 Upgrade YARP dependency to v0.11.0
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/constant_test.rb
  ruby-lsp.gemspec
  sorbet/rbi/gems/yarp@0.11.0.rbi
  sorbet/rbi/shims/yarp.rbi
  test/expectations/definition/class_reference.exp.json
  test/expectations/definition/constant_reference.exp.json
  test/expectations/hover/documented_class.exp.json
  test/expectations/hover/documented_constant.exp.json
  test/expectations/hover/documented_module.exp.json
  test/expectations/hover/documented_namespaced_class.exp.json
Labels: bugfix

#996 Bundle check before running update on custom bundle
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix

#998 Fix DocumentLink behaviour for removed gem
  lib/ruby_lsp/requests/document_link.rb
  test/fixtures/source_comment.rb
Labels: bugfix

#1001 Run version bump workflow on tag creation
  .github/workflows/version_bump.yml
Labels: chore

#1010 Exclude transitive development dependencies
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/test/configuration_test.rb
Labels: enhancement

#1021 Provide nesting and the index for hover extensions
  SERVER_EXTENSIONS.md
  lib/ruby_lsp/extension.rb
  lib/ruby_lsp/requests/hover.rb
  test/requests/hover_expectations_test.rb
Labels: breaking-change

#1024 Update argument order for CodeLens initializer
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/requests/code_lens.rb
  test/requests/code_lens_expectations_test.rb
Labels: chore

#1026 Add title to RDoc website
  Rakefile
Labels: chore

#1023 Handle constant aliases and ability to follow them
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/visitor.rb
  lib/ruby_indexer/test/constant_test.rb
Labels: enhancement

#1048 Ignore nesting when resolving top level constants
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix
