Repository Shopify/ruby-lsp, pull requests merged in 2024-12, with the labels that each got.

#2957 Print debugger output to the Ruby LSP output channel as well as the debug console
  vscode/src/debugger.ts
Labels: enhancement, vscode

#2961 Provide additional debugging help when the debugger exits with an error
  vscode/src/debugger.ts
Labels: enhancement, vscode

#2956 Update links for reporting issues
  jekyll/composed-bundle.markdown
  jekyll/index.markdown
  jekyll/troubleshooting.markdown
Labels: documentation, chore

#2950 Add intrinsics to roadmap
  jekyll/design-and-roadmap.markdown
Labels: documentation, chore

#2967 Add related code navigation to roadmap
  jekyll/design-and-roadmap.markdown
Labels: chore

#2954 Fix folding ranges when a line is surrounded by comments and contains code
  lib/ruby_lsp/listeners/folding_ranges.rb
  test/expectations/folding_ranges/block_comments_surround.exp.json
  test/fixtures/block_comments_surround.rb
Labels: bugfix, server

#2973 Add glyph for 'Run' code lenses
  lib/ruby_lsp/listeners/code_lens.rb
  test/expectations/code_lens/minitest_nested_classes_and_modules.exp.json
  test/expectations/code_lens/minitest_spec_tests.exp.json
  test/expectations/code_lens/minitest_tests.exp.json
  test/expectations/code_lens/minitest_with_dynamic_constant_path.exp.json
  test/expectations/code_lens/nested_minitest_tests.exp.json
  test/requests/code_lens_expectations_test.rb
Labels: enhancement, server

#2972 Github issue: https://github.com/Shopify/ruby-lsp/issues/2837
  vscode/grammars/ruby.cson.json
Labels: bugfix, vscode

#2979 Pass Ruby interpreter path when replacing process by launcher
  exe/ruby-lsp
Labels: bugfix, server

#2980 Avoid stubbing File.read to prevent flaky tests
  test/server_test.rb
Labels: chore

#2943 VSCode extension checks multiple install locations for `mise` binary
  vscode/src/ruby.ts
  vscode/src/ruby/mise.ts
Labels: enhancement, vscode

#2983 [docs] Recommend latest Bundler
  jekyll/troubleshooting.markdown
Labels: documentation

#2978 Fix debug platform inclusion for Windows
  lib/ruby_lsp/setup_bundler.rb
  test/integration_test.rb
Labels: bugfix, server

#2990 Fix command capitalization consistency
  .github/ISSUE_TEMPLATE/bug_template_vscode.yml
  vscode/package.json
Labels: chore, vscode

#2450 Add a new command to help users migrate launch.json configurations
  vscode/package.json
  vscode/src/common.ts
  vscode/src/debugger.ts
  vscode/src/rubyLsp.ts
Labels: enhancement, vscode

#2930 Enable spellcheck for TypeScript files
  cspell.jsonc
  project-words
  vscode/src/infoCollector.ts
  vscode/src/rubyLsp.ts
  vscode/src/status.ts
  vscode/src/test/suite/common.test.ts
  vscode/src/test/suite/status.test.ts
  vscode/src/testController.ts
Labels: chore

#2991 Add test helper methods from Rails add-on
  .rubocop.yml
  lib/ruby_lsp/test_helper.rb
Labels: enhancement, server
