Repository Shopify/ruby-lsp, pull requests merged in 2024-04, with the labels that each got.

#1869 Add ubuntu RVM path to list of possible installations
  vscode/src/ruby/rvm.ts
Labels: bugfix, vscode

#1855 Allow formatter addons to contribute diagnostics
  ADDONS.md
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/requests.rb
  lib/ruby_lsp/requests/diagnostics.rb
  lib/ruby_lsp/requests/formatting.rb
  lib/ruby_lsp/requests/request.rb
  lib/ruby_lsp/requests/support/formatter.rb
  lib/ruby_lsp/requests/support/formatter_runner.rb
  lib/ruby_lsp/requests/support/rubocop_diagnostics_runner.rb
  lib/ruby_lsp/requests/support/rubocop_formatter.rb
  lib/ruby_lsp/requests/support/rubocop_formatting_runner.rb
  lib/ruby_lsp/requests/support/syntax_tree_formatter.rb
  lib/ruby_lsp/server.rb
  test/requests/code_actions_formatting_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/diagnostics_test.rb
  test/requests/formatting_expectations_test.rb
  test/requests/formatting_test.rb
  test/server_test.rb
Labels: breaking-change, server

#1880 Avoid `require_relative` in `test_helper`
  test/test_helper.rb
Labels: chore

#1876 Enable `no-floating-promises` lint
  vscode/.eslintrc.json
  vscode/package.json
  vscode/src/client.ts
  vscode/src/dependenciesTree.ts
  vscode/src/ruby/mise.ts
  vscode/src/ruby/shadowenv.ts
  vscode/src/rubyLsp.ts
  vscode/src/telemetry.ts
  vscode/src/test/runTest.ts
  vscode/src/test/suite/ruby/mise.test.ts
  vscode/src/testController.ts
  vscode/src/workspace.ts
  vscode/yarn.lock
Labels: bugfix, vscode

#1889 Remove verbose or debug environment variables from Ruby env
  vscode/src/ruby.ts
  vscode/src/test/suite/debugger.test.ts
  vscode/src/test/suite/ruby.test.ts
Labels: bugfix, vscode

#1890 Fix troubleshooting container link
  TROUBLESHOOTING.md
Labels: chore

#1894 Avoid activating debugger in tests by default
  dev.yml
  test/test_helper.rb
Labels: chore, server

#1901 Synchronize didOpen and didClose notifications
  lib/ruby_lsp/server.rb
Labels: bugfix, server

#1877 Add mason.nvim config steps to EDITORS.md
  EDITORS.md
Labels: documentation, other

#1904 Remove `Singleton` from formatters
  ADDONS.md
  lib/ruby_lsp/requests/support/rubocop_formatter.rb
  lib/ruby_lsp/requests/support/syntax_tree_formatter.rb
  lib/ruby_lsp/server.rb
  test/requests/code_actions_formatting_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/diagnostics_test.rb
  test/requests/formatting_expectations_test.rb
  test/requests/formatting_test.rb
  test/server_test.rb
Labels: breaking-change, server

#1831 Enhance version manager config to accept more fields
  vscode/README.md
  vscode/VERSION_MANAGERS.md
  vscode/package.json
  vscode/src/common.ts
  vscode/src/extension.ts
  vscode/src/ruby.ts
  vscode/src/rubyLsp.ts
  vscode/src/status.ts
  vscode/src/telemetry.ts
  vscode/src/test/suite/client.test.ts
  vscode/src/test/suite/debugger.test.ts
  vscode/src/test/suite/ruby.test.ts
  vscode/src/test/suite/status.test.ts
Labels: vscode, other

#1916 Set codeowners to ruby-dx
  .github/CODEOWNERS
Labels: chore

#1923 Migrate manager config before activating
  vscode/src/extension.ts
Labels: bugfix, vscode

#1931 Fix troubleshooting status center logo link
  TROUBLESHOOTING.md
Labels: documentation

#1929 Allow request ids to be strings
  lib/ruby_lsp/utils.rb
Labels: server, other

#1960 Increase timeout for tests
  vscode/src/test/suite/client.test.ts
Labels: chore, vscode

#1926 Avoid memoizing dependencies
  lib/ruby_lsp/global_state.rb
  test/global_state_test.rb
Labels: server, other

#1962 Upgrade to Ruby 3.3.1
  .ruby-version
  vscode/src/test/rubyVersion.ts
  vscode/src/test/suite/debugger.test.ts
  vscode/src/test/suite/ruby/chruby.test.ts
  vscode/src/test/suite/ruby/rubyInstaller.test.ts
  vscode/src/test/suite/ruby/shadowenv.test.ts
Labels: chore

#1961 Support go to definition for unknown receiver calls
  lib/ruby_lsp/listeners/definition.rb
  test/requests/definition_expectations_test.rb
Labels: enhancement, server

#1978 Make module tracking lazy
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
Labels: server, other

#1982 Support symbol procs in definition
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/requests/definition.rb
  test/requests/definition_expectations_test.rb
Labels: enhancement, server

#1993 Update auto assign workflow to reflect team change
  .github/workflows/auto_assign.yml
Labels: chore
