Repository Shopify/ruby-lsp, pull requests merged in 2024-11, with the labels that each got.

#2816 Extract progress notifications to helpers
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/utils.rb
Labels: server, other

#2814 Ensure we're handling client responses for window show message
  lib/ruby_lsp/server.rb
  test/server_test.rb
Labels: bugfix, server

#2818 Use the same debounced restart for all watchers
  vscode/src/workspace.ts
Labels: bugfix, vscode

#2826 Add feature flag support to GlobalState
  lib/ruby_lsp/global_state.rb
  test/global_state_test.rb
  vscode/src/client.ts
Labels: enhancement, server

#2849 Ensure top level scripts are indexed
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/test/configuration_test.rb
Labels: bugfix, server

#2853 Log when trying to format files outside of workspace
  lib/ruby_lsp/server.rb
Labels: server, other

#2859 Use predicates in tests for checking visibility
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/constant_test.rb
  lib/ruby_indexer/test/method_test.rb
Labels: chore

#2864 Prevent full indexing (`index_all`) from being called multiple times
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: enhancement, server

#2806 Fix documentation reference when methods are too close
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/method_test.rb
  test/requests/completion_resolve_test.rb
Labels: bugfix, server

#2879 Show multi-root workspace warning as progress instead
  vscode/src/rubyLsp.ts
Labels: vscode, other

#2885 Add callout on editors section of website about Mason risks
  jekyll/editors.markdown
Labels: documentation

#2883 Only include workspace name as part of telemetry
  vscode/src/client.ts
Labels: vscode, other

#2835 Allow individual version managers to trigger manual Ruby selection
  vscode/src/ruby.ts
  vscode/src/ruby/chruby.ts
  vscode/src/ruby/none.ts
  vscode/src/ruby/versionManager.ts
  vscode/src/test/suite/ruby/asdf.test.ts
  vscode/src/test/suite/ruby/chruby.test.ts
  vscode/src/test/suite/ruby/custom.test.ts
  vscode/src/test/suite/ruby/mise.test.ts
  vscode/src/test/suite/ruby/none.test.ts
  vscode/src/test/suite/ruby/rbenv.test.ts
  vscode/src/test/suite/ruby/rubyInstaller.test.ts
  vscode/src/test/suite/ruby/rvm.test.ts
  vscode/src/test/suite/ruby/shadowenv.test.ts
Labels: vscode, other

#2880 Start returning composed bundle environment from initialize request
  exe/ruby-lsp-launcher
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/server.rb
  project-words
  test/server_test.rb
Labels: server, other

#2858 Support `private_class_method` in the indexer
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/method_test.rb
Labels: enhancement, server

#2900 Make `enabled_feature?` return true when all flags are enabled
  lib/ruby_lsp/global_state.rb
  test/global_state_test.rb
Labels: bugfix, vscode

#2923 Add note to docs about unsaved files
  jekyll/index.markdown
Labels: documentation, server

#2924 Rename indexables to indexable_uris
  exe/ruby-lsp
  exe/ruby-lsp-check
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/configuration_test.rb
Labels: chore

#2927 Use Entry#uri where possible instead of file path
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/requests/prepare_type_hierarchy.rb
  lib/ruby_lsp/requests/rename.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/requests/type_hierarchy_supertypes.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
Labels: server, other

#2931 Allow opting into specific feature flags
  vscode/src/common.ts
  vscode/src/test/suite/common.test.ts
Labels: bugfix, vscode

#2928 Test for presence of shadowenv binary before running Shadowenv suite
  vscode/src/test/suite/ruby/shadowenv.test.ts
Labels: chore

#2932 Chruby test suite looks for ruby binary in multiple locations
  vscode/src/test/suite/ruby/chruby.test.ts
Labels: chore

#2937 Avoid excluding transitive dependencies of default dependencies
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/test/configuration_test.rb
  project-words
Labels: bugfix, server
