Repository Shopify/ruby-lsp, pull requests merged in 2024-02, with the labels that each got.

#1363 Explain why `to_spec` may be `nil`
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
Labels: chore

#1368 Categorize hover content
  lib/ruby_lsp/listeners/hover.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/response_builders/hover.rb
  test/requests/hover_expectations_test.rb
Labels: breaking-change

#1369 Handle nested method calls in signature help without adjusting positions
  lib/ruby_lsp/requests/signature_help.rb
  test/requests/signature_help_test.rb
Labels: bugfix

#1370 Use sorbet-static to determine if Sorbet is present
  lib/ruby_lsp/requests/support/dependency_detector.rb
Labels: bugfix

#1378 Update RubyLsp::Requests::CodeLens demo gif
  lib/ruby_lsp/requests/code_lens.rb
  misc/code_lens.gif
Labels: documentation

#1400 Allow addons to define initialize
  lib/ruby_lsp/addon.rb
  test/addon_test.rb
  test/expectations/expectations_test_runner.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
Labels: bugfix

#1408 Add note about indexing
  README.md
Labels: documentation

#1379 Update documentation for add-ons
  ADDONS.md
Labels: documentation, addons

#1417 Move approval and auto-merge into GH action step
  .github/workflows/version_bump.yml
Labels: chore

#1407 Monorepo
  vscode/.devcontainer/devcontainer.json
  vscode/.eslintrc.json
  vscode/.github/CODEOWNERS
  vscode/.github/ISSUE_TEMPLATE/bug_template.yml
  vscode/.github/ISSUE_TEMPLATE/feature_template.yml
  vscode/.github/dependabot.yml
  vscode/.github/pull_request_template.md
  vscode/.github/release.yml
  vscode/.github/workflows/automate_dependabot.yml
  vscode/.github/workflows/ci.yml
  vscode/.github/workflows/cla.yml
  vscode/.github/workflows/close_stale_issues_and_prs.yml
  vscode/.github/workflows/publish.yml
  vscode/.gitignore
  vscode/.prettierignore
  vscode/.vscode/extensions.json
  vscode/.vscode/launch.json
  vscode/.vscode/settings.json
  vscode/.vscode/tasks.json
  vscode/.vscodeignore
  vscode/.yarnrc
  vscode/CODE_OF_CONDUCT.md
  vscode/LICENSE.txt
  vscode/README.md
  vscode/TROUBLESHOOTING.md
  vscode/VERSION_MANAGERS.md
  vscode/dev.yml
  vscode/extras/ruby_lsp_demo.gif
  vscode/extras/ruby_lsp_status_center.png
  vscode/grammars/erb.cson.json
  vscode/grammars/ruby.cson.json
  vscode/icon.png
  vscode/languages/erb.json
  vscode/languages/ruby.json
  vscode/package.json
  vscode/snippets.json
  vscode/src/client.ts
  vscode/src/common.ts
  vscode/src/debugger.ts
  vscode/src/dependenciesTree.ts
  vscode/src/documentProvider.ts
  vscode/src/extension.ts
  vscode/src/ruby.ts
  vscode/src/rubyLsp.ts
  vscode/src/status.ts
  vscode/src/telemetry.ts
  vscode/src/test/runTest.ts
  vscode/src/test/suite/client.test.ts
  vscode/src/test/suite/debugger.test.ts
  vscode/src/test/suite/grammars.test.ts
  vscode/src/test/suite/index.ts
  vscode/src/test/suite/ruby.test.ts
  vscode/src/test/suite/status.test.ts
  vscode/src/test/suite/telemetry.test.ts
  vscode/src/test/suite/workspaceChannel.test.ts
  vscode/src/testController.ts
  vscode/src/workspace.ts
  vscode/src/workspaceChannel.ts
  vscode/tsconfig.json
  vscode/yarn.lock
Labels: chore

#1393 Add SimpleCov
  Gemfile
  Gemfile.lock
  sorbet/rbi/gems/simplecov@0.22.0.rbi
  test/test_helper.rb
Labels: chore

#1420 Improve release note automation for monorepo
  .github/release.yml
  .github/workflows/publish.yml
  .github/workflows/release.yml
  .github/workflows/require_labels.yml
Labels: chore
