Repository Shopify/ruby-lsp, pull requests merged in 2024-09, with the labels that each got.

#2423 Replace IndexablePath with ResourceUri concept
  exe/ruby-lsp
  exe/ruby-lsp-check
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/indexable_path.rb
  lib/ruby_indexer/lib/ruby_indexer/resource_uri.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_indexer/test/test_case.rb
  lib/ruby_indexer/test/uri_test.rb
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/test_helper.rb
  rakelib/index.rake
  sorbet/rbi/shims/uri.rbi
  test/requests/completion_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/workspace_symbol_test.rb
  test/server_test.rb
  test/type_inferrer_test.rb
Labels: server, other

#2523 Revert "Replace IndexablePath with ResourceUri concept"
  exe/ruby-lsp
  exe/ruby-lsp-check
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/indexable_path.rb
  lib/ruby_indexer/lib/ruby_indexer/resource_uri.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_indexer/test/test_case.rb
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/test_helper.rb
  rakelib/index.rake
  sorbet/rbi/shims/uri.rbi
  test/requests/completion_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/support/uri_test.rb
  test/requests/workspace_symbol_test.rb
  test/server_test.rb
  test/type_inferrer_test.rb
Labels: server, other

#2537 Ignore `.vscode-tests` for eslint
  vscode/eslint.config.mjs
Labels: chore

#2522 Fix minitest code lens filter patterns
  CONTRIBUTING.md
  lib/ruby_lsp/listeners/code_lens.rb
  test/expectations/code_lens/minitest_nested_classes_and_modules.exp.json
  test/expectations/code_lens/minitest_spec_tests.exp.json
  test/expectations/code_lens/minitest_tests.exp.json
  test/expectations/code_lens/minitest_with_dynamic_constant_path.exp.json
  test/expectations/code_lens/nested_minitest_tests.exp.json
  test/fixtures/minitest_spec_tests.rb
  test/requests/support/expectations_test_runner.rb
  vscode/src/testController.ts
Labels: bugfix, server

#2542 Turn on semantic highlighting for ERB
  lib/ruby_lsp/requests/semantic_highlighting.rb
Labels: enhancement, server

#2539 Allow launching the server in debug mode
  vscode/package.json
  vscode/src/client.ts
  vscode/src/common.ts
  vscode/src/rubyLsp.ts
  vscode/src/workspace.ts
Labels: vscode, other

#2536 Uses Jekyll to generate the documentation
  .github/workflows/publish_docs.yml
  .rubocop.yml
  CONTRIBUTING.md
  Gemfile.lock
  README.md
  jekyll/.gitignore
  jekyll/404.html
  jekyll/Gemfile
  jekyll/Gemfile.lock
  jekyll/_config.yml
  jekyll/icon.png
  jekyll/images/ruby-lsp-completion-demo-basic.mp4
  jekyll/images/ruby-lsp-definition-demo-basic.mp4
  jekyll/images/ruby-lsp-definition-demo-multi-source.mp4
  jekyll/images/ruby-lsp-erb-support-demo.mp4
  jekyll/images/ruby-lsp-hover-demo-basic.mp4
  jekyll/images/ruby-lsp-signature-help-demo-basic.mp4
  jekyll/images/ruby-lsp-type-hierarchy-demo.mp4
  jekyll/index.markdown
  sorbet/config
Labels: documentation, server

#2559 Include Ruby LSP Rails' documentation
  jekyll/_config.yml
  jekyll/images/ruby-lsp-rails-controller-action-to-route.gif
  jekyll/images/ruby-lsp-rails-controller-action-to-view.gif
  jekyll/images/ruby-lsp-rails-debug.gif
  jekyll/images/ruby-lsp-rails-destroy-command.gif
  jekyll/images/ruby-lsp-rails-document-symbol-ar-model.gif
  jekyll/images/ruby-lsp-rails-file-operations-icon.gif
  jekyll/images/ruby-lsp-rails-generate-command.gif
  jekyll/images/ruby-lsp-rails-go-to-ar-associations.gif
  jekyll/images/ruby-lsp-rails-go-to-ar-dsl-definitions.gif
  jekyll/images/ruby-lsp-rails-go-to-route-definitions.gif
  jekyll/images/ruby-lsp-rails-run-in-terminal.gif
  jekyll/images/ruby-lsp-rails-run.gif
  jekyll/images/ruby-lsp-rails-test-document-symbol.gif
  jekyll/index.markdown
  jekyll/rails-addon.markdown
Labels: documentation, addons, server

#2551 Add support for delegating completion requests for ERB files
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/erb_document.rb
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/rbs_document.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/request.rb
  lib/ruby_lsp/ruby_document.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/utils.rb
  test/erb_document_test.rb
  test/rbs_document_test.rb
  test/requests/on_type_formatting_test.rb
  test/ruby_document_test.rb
  vscode/src/client.ts
  vscode/src/rubyLsp.ts
  vscode/src/test/suite/client.test.ts
  vscode/src/workspace.ts
Labels: enhancement, server

#2562 Move `stub_bundle_with_env` inside `Bundler.with_unbundled_env`
  test/setup_bundler_test.rb
Labels: chore

#2552 Use separator for activation script result
  vscode/src/ruby/asdf.ts
  vscode/src/ruby/chruby.ts
  vscode/src/ruby/custom.ts
  vscode/src/ruby/mise.ts
  vscode/src/ruby/none.ts
  vscode/src/ruby/rbenv.ts
  vscode/src/ruby/rvm.ts
  vscode/src/ruby/shadowenv.ts
  vscode/src/ruby/versionManager.ts
  vscode/src/test/suite/ruby/asdf.test.ts
  vscode/src/test/suite/ruby/custom.test.ts
  vscode/src/test/suite/ruby/mise.test.ts
  vscode/src/test/suite/ruby/none.test.ts
  vscode/src/test/suite/ruby/rbenv.test.ts
  vscode/src/test/suite/ruby/rubyInstaller.test.ts
  vscode/src/test/suite/ruby/rvm.test.ts
Labels: bugfix, vscode

#2567 Separate Jekyll CI from regular CI and add dependabot
  .github/dependabot.yml
  .github/workflows/ci.yml
  .github/workflows/verify_docs.yml
Labels: chore

#2573 Fix image references for features
  jekyll/index.markdown
Labels: chore

#2563 Delegate all possible features for ERB
  dev.yml
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/signature_help.rb
  lib/ruby_lsp/server.rb
  test/requests/document_highlight_expectations_test.rb
  vscode/src/client.ts
  vscode/src/test/suite/client.test.ts
Labels: enhancement, vscode, server

#2576 Minor docs fixes
  jekyll/index.markdown
Labels: chore

#2577 Run doc verify as part of CI
  .github/workflows/ci.yml
  .github/workflows/verify_docs.yml
Labels: chore

#2584 Delete comment prefix when lazy fetching
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
Labels: bugfix, server

#2586 Fix completion for inherited constants
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_lsp/listeners/completion.rb
  test/requests/completion_test.rb
Labels: bugfix, server

#2589 Remove all autoloads
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/requests.rb
  lib/ruby_lsp/response_builders.rb
  test/requests/formatting_test.rb
Labels: server, other

#2591 Remove --experimental flag
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: chore, server

#2598 Fix body line height for code
  jekyll/_sass/custom/_custom.scss
Labels: chore

#2600 Remove version manager setting migration code
  vscode/src/extension.ts
Labels: vscode, other

#2599 Stabilize guessed types
  jekyll/design-and-roadmap.markdown
  jekyll/index.markdown
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/type_inferrer.rb
Labels: server, other

#2606 Add Social Media Preview Image for Ruby LSP Docs
  jekyll/_config.yml
Labels: documentation, chore

#2617 Add heredoc delimiter documentation on hover
  lib/ruby_lsp/listeners/hover.rb
  test/expectations/folding_ranges/squiggly_heredoc.exp.json
  test/expectations/hover/dash_heredoc.exp.json
  test/expectations/hover/plain_heredoc.exp.json
  test/expectations/hover/squiggly_heredoc.exp.json
  test/expectations/selection_ranges/squiggly_heredoc.exp.json
  test/fixtures/dash_heredoc.rb
  test/fixtures/plain_heredoc.rb
  test/fixtures/squiggly_heredoc.rb
Labels: enhancement, server

#2620 Support plain heredocs in on type formatting
  lib/ruby_lsp/requests/on_type_formatting.rb
  test/requests/on_type_formatting_test.rb
Labels: bugfix, server

#2625 Fix wording (inspection -> introspection)
  jekyll/rails-add-on.markdown
Labels: chore

#2631 Account for RBS untyped functions
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb
  lib/ruby_indexer/test/rbs_indexer_test.rb
  sorbet/rbi/gems/rbs@3.6.0.rbi
  sorbet/rbi/gems/rexml@3.3.6.rbi
  sorbet/rbi/gems/strscan@3.1.0.rbi
Labels: bugfix, server

#2633 Add index troubleshooting steps
  jekyll/troubleshooting.markdown
  lib/ruby_lsp/server.rb
  test/server_test.rb
Labels: documentation, server
