Repository Shopify/ruby-lsp, pull requests merged in 2024-01, with the labels that each got.

#1275 Upgrade to Ruby 3.3
  .github/workflows/ci.yml
  .github/workflows/version_bump.yml
  dev.yml
Labels: chore

#1278 Document index configuration file
  README.md
Labels: documentation

#1281 Add Request class to standardise request interface
  lib/ruby_lsp/check_docs.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/listener.rb
  lib/ruby_lsp/requests.rb
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/code_actions.rb
  lib/ruby_lsp/requests/diagnostics.rb
  lib/ruby_lsp/requests/formatting.rb
  lib/ruby_lsp/requests/on_type_formatting.rb
  lib/ruby_lsp/requests/request.rb
  lib/ruby_lsp/requests/selection_ranges.rb
  lib/ruby_lsp/requests/show_syntax_tree.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  test/requests/code_action_resolve_expectations_test.rb
  test/requests/code_actions_expectations_test.rb
  test/requests/code_actions_formatting_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/diagnostics_test.rb
  test/requests/formatting_expectations_test.rb
  test/requests/formatting_test.rb
  test/requests/on_type_formatting_test.rb
  test/requests/selection_ranges_expectations_test.rb
  test/requests/workspace_symbol_test.rb
Labels: chore

#1294 Show method parameters as completion details
  lib/ruby_lsp/requests/completion.rb
  test/requests/completion_test.rb
Labels: enhancement

#1297 Rename Request#response to Request#perform
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/code_actions.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/diagnostics.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/requests/document_symbol.rb
  lib/ruby_lsp/requests/folding_ranges.rb
  lib/ruby_lsp/requests/formatting.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/inlay_hints.rb
  lib/ruby_lsp/requests/on_type_formatting.rb
  lib/ruby_lsp/requests/request.rb
  lib/ruby_lsp/requests/selection_ranges.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
  lib/ruby_lsp/requests/show_syntax_tree.rb
  lib/ruby_lsp/requests/signature_help.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  test/expectations/expectations_test_runner.rb
  test/requests/code_action_resolve_expectations_test.rb
  test/requests/code_actions_expectations_test.rb
  test/requests/code_actions_formatting_test.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/diagnostics_test.rb
  test/requests/document_highlight_expectations_test.rb
  test/requests/document_link_expectations_test.rb
  test/requests/folding_ranges_expectations_test.rb
  test/requests/formatting_expectations_test.rb
  test/requests/formatting_test.rb
  test/requests/inlay_hints_expectations_test.rb
  test/requests/on_type_formatting_test.rb
  test/requests/selection_ranges_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
  test/requests/workspace_symbol_test.rb
Labels: chore

#1315 Skip comment parsing for invalid encodings
  lib/ruby_indexer/lib/ruby_indexer/collector.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
Labels: bugfix

#1311 Restructure DocumentSymbol request
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/listeners/document_symbol.rb
  lib/ruby_lsp/requests/document_symbol.rb
  lib/ruby_lsp/response.rb
  test/requests/document_symbol_expectations_test.rb
Labels: breaking-change, addons

#1332 Restructure definition request to use response builder
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/response_builders.rb
  lib/ruby_lsp/response_builders/definition.rb
  test/requests/definition_expectations_test.rb
Labels: breaking-change

#1341 Gemfile cleanup
  Gemfile
Labels: chore

#1337 Fully adopt the new response builder pattern and remove the Listener class
  lib/rubocop/cop/ruby_lsp/use_register_with_handler_method.rb
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/check_docs.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/listener.rb
  lib/ruby_lsp/listeners/code_lens.rb
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/listeners/document_highlight.rb
  lib/ruby_lsp/listeners/document_link.rb
  lib/ruby_lsp/listeners/folding_ranges.rb
  lib/ruby_lsp/listeners/inlay_hints.rb
  lib/ruby_lsp/listeners/signature_help.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/document_link.rb
  lib/ruby_lsp/requests/folding_ranges.rb
  lib/ruby_lsp/requests/inlay_hints.rb
  lib/ruby_lsp/requests/signature_help.rb
  lib/ruby_lsp/response_builders.rb
  lib/ruby_lsp/response_builders/code_lens.rb
  lib/ruby_lsp/response_builders/collection_response_builder.rb
  lib/ruby_lsp/response_builders/definition.rb
  lib/ruby_lsp/response_builders/response_builder.rb
  lib/ruby_lsp/response_builders/signature_help.rb
  test/expectations/definition/requires.exp.json
  test/fixtures/requires.rb
  test/requests/definition_expectations_test.rb
  test/rubocop/cop/ruby_lsp/use_register_with_handler_method_test.rb
Labels: breaking-change
