Repository Shopify/ruby-lsp, pull requests merged in 2024-06, with the labels that each got.

#2123 Run labels check only after PR approval
  .github/workflows/require_labels.yml
Labels: chore, server

#2128 Fix duplicate nesting when targetting classes/modules
  lib/ruby_lsp/document.rb
  test/ruby_document_test.rb
Labels: bugfix, server

#2124 Handle unsaved files in main language server client
  vscode/src/client.ts
  vscode/src/rubyLsp.ts
  vscode/src/workspace.ts
Labels: bugfix, vscode

#2115 Add CallNode field to NodeContext
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/listeners/hover.rb
  lib/ruby_lsp/node_context.rb
  lib/ruby_lsp/requests/definition.rb
  test/ruby_document_test.rb
Labels: chore

#2138 Add link to VS Code extension README
  README.md
Labels: chore, vscode

#2141 Add Homebrew note for ASDF
  VERSION_MANAGERS.md
Labels: documentation, server

#2129 Add `case` statement to VS Code snippets
  vscode/snippets.json
Labels: enhancement, vscode

#2133 Standardize version manager script execution
  vscode/package.json
  vscode/src/ruby/asdf.ts
  vscode/src/ruby/chruby.ts
  vscode/src/ruby/custom.ts
  vscode/src/ruby/mise.ts
  vscode/src/ruby/none.ts
  vscode/src/ruby/rbenv.ts
  vscode/src/ruby/rvm.ts
  vscode/src/ruby/shadowenv.ts
  vscode/src/ruby/versionManager.ts
  vscode/src/test/suite/ruby/custom.test.ts
  vscode/src/test/suite/ruby/mise.test.ts
  vscode/src/test/suite/ruby/none.test.ts
  vscode/src/test/suite/ruby/rbenv.test.ts
  vscode/src/test/suite/ruby/rvm.test.ts
Labels: bugfix, vscode

#2145 Ensure update server gem command updates the locked server
  vscode/src/rubyLsp.ts
  vscode/src/workspace.ts
Labels: bugfix, vscode

#2132 Index core classes using RBS
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_indexer/test/rbs_indexer_test.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/server.rb
  ruby-lsp.gemspec
  sorbet/rbi/gems/rbs@3.4.4.rbi
Labels: enhancement, server

#2146 Run label check on any PR review
  .github/workflows/require_labels.yml
Labels: chore

#2153 Filter instance variable owners before deduping
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#2150 Add lazyvim to editors.md
  EDITORS.md
Labels: documentation

#2154 Correct path for enabling ruby-lsp with LazyVim
  EDITORS.md
Labels: documentation, server

#1911 Specify in Readme that global rubocop command is not supported
  vscode/README.md
Labels: documentation

#2126 Detect RuboCop as the formatter when it is only a transitive depenency
  lib/ruby_lsp/global_state.rb
  test/global_state_test.rb
  test/server_test.rb
Labels: bugfix, server

#2158 Remove non-existing algorithm path for constant resolution
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#2159 Move Bundler and Minitest outside development group
  Gemfile
Labels: chore

#2148 Build complete ancestors list with RBS classes and modules
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/constant_test.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_indexer/test/method_test.rb
  lib/ruby_indexer/test/rbs_indexer_test.rb
  lib/ruby_indexer/test/test_case.rb
  lib/ruby_lsp/server.rb
Labels: enhancement, server

#2097 Rescue SystemStackError while indexing
  lib/ruby_indexer/lib/ruby_indexer/index.rb
Labels: bugfix, server

#2166 Update Homebrew note for `asdf `
  VERSION_MANAGERS.md
Labels: documentation, server

#2175 Fix incorrect parent class assignment for Object and BasicObject
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#2171 Offer RuboCop autocorrection for contextual offenses
  lib/ruby_lsp/requests/support/rubocop_diagnostic.rb
  test/expectations/diagnostics/rubocop_contextual_autocorrect.exp.json
  test/fixtures/rubocop_contextual_autocorrect.rb
Labels: enhancement, server

#2179 Show method parameters on hover
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_lsp/listeners/hover.rb
  test/requests/hover_expectations_test.rb
  test/requests/signature_help_test.rb
Labels: bugfix, server

#2182 Exclude singleton classes from name based searches
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb
  lib/ruby_indexer/test/index_test.rb
Labels: server, other

#2185 Allow `Entry::Method` to be initialized with `Entry::Parameter`s
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb
Labels: chore, server

#2180 Display addons status in the control panel
  lib/ruby_lsp/server.rb
  test/server_test.rb
  vscode/src/client.ts
  vscode/src/common.ts
  vscode/src/status.ts
  vscode/src/test/suite/status.test.ts
  vscode/src/workspace.ts
Labels: enhancement, vscode

#2195 Fix link to Ruby LSP plugin in EDITORS.md
  EDITORS.md
Labels: documentation

#2186 Remember singleton nesting and method nesting when locating nodes
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/node_context.rb
  test/ruby_document_test.rb
Labels: enhancement, server

#2203 Upgrade Sorbet
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  lib/ruby_lsp/type_inferrer.rb
Labels: chore

#2205 Use quickpick UI to display addons list
  vscode/package.json
  vscode/src/common.ts
  vscode/src/rubyLsp.ts
  vscode/src/status.ts
  vscode/src/test/suite/status.test.ts
Labels: enhancement, addons, vscode

#2208 Search aliased namespaces in the top level too
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#2209 Move experimental features into global state
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/store.rb
  test/global_state_test.rb
Labels: server, other

#2213 Document manager activation for other editors
  EDITORS.md
Labels: documentation

#2212 Fix chruby release candidate ordering
  vscode/src/ruby/chruby.ts
  vscode/src/test/suite/ruby/chruby.test.ts
Labels: bugfix, vscode

#2216 Provide a way for addon developers to get an addon by name
  lib/ruby_lsp/addon.rb
  test/addon_test.rb
Labels: enhancement, server

#2221 Introduce `Entry::Signature` to support overloading
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
Labels: chore, server

#2092 Add configuration options for third-party formatters
  vscode/package.json
Labels: enhancement, vscode
