Repository Shopify/ruby-lsp, pull requests merged in 2024-03, with the labels that each got.

#1437 Add Prism warnings in diagnostics
  lib/ruby_lsp/requests/diagnostics.rb
  test/expectations/diagnostics/syntax_diagnostics.exp.json
  test/fixtures/syntax_diagnostics.rb
  test/requests/diagnostics_expectations_test.rb
Labels: enhancement

#1441 Extract `Notification.window_show_error`
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/utils.rb
Labels: chore

#1453 Support RuboCop's LSP mode
  lib/ruby_lsp/requests/support/rubocop_runner.rb
Labels: enhancement, server

#1523 Enable Dependabot for GitHub Actions
  .github/dependabot.yml
Labels: chore

#1589 Remove pattern from document selector
  vscode/src/client.ts
Labels: bugfix, vscode

#1590 Exclude the `tmp` directory from indexing by default
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
Labels: server, other

#1593 Set error to false on workspace restart
  vscode/src/workspace.ts
Labels: bugfix, vscode

#1592 Use original Bundler environment to find workspace dependencies
  lib/ruby_lsp/executor.rb
Labels: bugfix, server

#1595 Remove fs usages in debugger client
  vscode/src/debugger.ts
  vscode/src/test/suite/debugger.test.ts
Labels: bugfix, vscode

#1602 Remove unnecessary question mark from Ruby version URL
  vscode/src/ruby.ts
Labels: chore

#1529 Implement Mise as a manager object
  vscode/src/ruby.ts
  vscode/src/ruby/mise.ts
  vscode/src/test/suite/ruby/mise.test.ts
Labels: enhancement, vscode

#1607 Use ruby as default engine when searching for chruby installation
  vscode/src/ruby/chruby.ts
  vscode/src/test/suite/ruby/chruby.test.ts
Labels: bugfix, vscode

#1606 Fix no code lenses for minitest specs with constant paths
  lib/ruby_lsp/listeners/code_lens.rb
  test/expectations/code_lens/minitest_spec_tests.exp.json
  test/fixtures/minitest_spec_tests.rb
Labels: bugfix, server

#1383 Indexed included modules on namespaces
  lib/ruby_indexer/lib/ruby_indexer/collector.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
Labels: enhancement, server

#1444 Add Rake document symbols
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/listeners/document_symbol.rb
  lib/ruby_lsp/requests/document_symbol.rb
  test/expectations/document_symbol/not_rake.json
  test/expectations/document_symbol/rake.exp.json
  test/expectations/expectations_test_runner.rb
  test/fixtures/not_rake.rb
  test/fixtures/rake.rake
  test/requests/document_symbol_expectations_test.rb
Labels: enhancement, server

#1796 Implement Windows activation as a manager object
  vscode/src/ruby.ts
  vscode/src/ruby/chruby.ts
  vscode/src/ruby/rubyInstaller.ts
  vscode/src/test/suite/ruby/rubyInstaller.test.ts
Labels: enhancement, vscode

#1648 Refactor refactor into server and base server
  exe/ruby-lsp-check
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/dependency_detector.rb
  lib/ruby_lsp/executor.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/utils.rb
  test/addon_test.rb
  test/executor_test.rb
  test/expectations/definition/requires.exp.json
  test/expectations/expectations_test_runner.rb
  test/fixtures/requires.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/completion_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
  test/requests/show_syntax_tree_test.rb
  test/requests/signature_help_test.rb
  test/server_test.rb
  test/test_helper.rb
Labels: server, other

#1799 Add logging note to troubleshooting docs
  TROUBLESHOOTING.md
Labels: documentation, server

#1801 No-op Sorbet type assertions
  .rubocop.yml
  exe/ruby-lsp
  exe/ruby-lsp-check
  lib/ruby_lsp/disable_sorbet.rb
  sorbet/rbi/shims/sorbet.rbi
Labels: server, other

#1802 Extract more of the Sorbet runtime loading into the separate file
  .rubocop.yml
  exe/ruby-lsp
  exe/ruby-lsp-check
  lib/ruby_lsp/disable_sorbet.rb
  lib/ruby_lsp/load_sorbet.rb
Labels: chore

#1805 Fix lazy document parsing and error reporting
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/utils.rb
Labels: bugfix, server

#1813 Check if path exists before adding spec code lens
  lib/ruby_lsp/listeners/code_lens.rb
  test/requests/code_lens_expectations_test.rb
Labels: bugfix, server

#1807 Remove unused assignment in ExpectationsTestRunner
  test/expectations/expectations_test_runner.rb
Labels: chore, server

#1817 Update warning block syntax
  ADDONS.md
Labels: documentation, server

#1816 Enable add-ons to extend completion
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/requests/completion.rb
  test/expectations/expectations_test_runner.rb
  test/requests/completion_test.rb
  test/test_helper.rb
Labels: enhancement, addons, server

#1815 Migrate integration tests to use the client
  test/integration_test.rb
  vscode/src/test/suite/client.test.ts
Labels: chore

#1811 Implement Rbenv activation as a manager object
  vscode/src/ruby.ts
  vscode/src/ruby/rbenv.ts
  vscode/src/test/suite/ruby/rbenv.test.ts
Labels: enhancement, vscode

#1814 Allow config to be passed into Indexer
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_lsp/server.rb
  test/server_test.rb
Labels: chore, server

#1830 Centralize Ruby Version to `.ruby-version`
  .github/workflows/ci.yml
  .github/workflows/lsp_check.yml
  .github/workflows/version_bump.yml
  .rubocop.yml
Labels: chore

#1798 Add support for completionItem/resolve
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/requests.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/completion_resolve.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/server.rb
  test/requests/completion_resolve_test.rb
Labels: enhancement, server

#1839 Enable ruby language on more file types
  vscode/package.json
Labels: enhancement, vscode

#1828 Implement RVM as a manager object
  vscode/src/ruby.ts
  vscode/src/ruby/rvm.ts
  vscode/src/test/suite/ruby/rvm.test.ts
Labels: enhancement, vscode

#1601 Prepend vscode for relative image references
  vscode/README.md
  vscode/package.json
Labels: bugfix, vscode

#1846 Add authors in changelog automation
  .github/workflows/publish.yml
  .github/workflows/release.yml
Labels: chore

#1848 Return early when building dependencies view if no client
  vscode/src/dependenciesTree.ts
Labels: bugfix, vscode

#1820 Indexed prepended modules on namespaces
  lib/ruby_indexer/lib/ruby_indexer/collector.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
Labels: enhancement, server

#1854 Pass global state via Addon#activate instead of listener creation methods
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/test_helper.rb
  test/addon_test.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/completion_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
Labels: breaking-change, addons, server
