Repository Shopify/ruby-lsp, pull requests merged in 2024-05, with the labels that each got.

#1972 Document how addons can listen for file changes
  ADDONS.md
Labels: documentation, server

#2002 Fix markdown syntax for docs
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
Labels: chore, server

#2004 Allow omitting patch in .ruby-version
  vscode/src/ruby/chruby.ts
  vscode/src/test/suite/ruby/chruby.test.ts
Labels: enhancement, vscode

#2005 Add --time-index flag for timing index
  exe/ruby-lsp
Labels: chore, server

#2008 Replace RubyIndexer::Collector with RubyIndexer::DeclarationListener
  exe/ruby-lsp-check
  exe/ruby-lsp-doctor
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/constant_test.rb
  lib/ruby_indexer/test/method_test.rb
Labels: enhancement, server

#2025 Use owner stack to associate owners to methods
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/method_test.rb
Labels: bugfix, server

#2030 Add RubyMine note
  EDITORS.md
Labels: documentation, server

#2035 Add note about logging setting
  .vscode/settings.json
Labels: chore

#2037 Add note about Zed editor
  EDITORS.md
Labels: documentation

#2068 Remove notes related to neovim 0.9 and cleanup docs
  EDITORS.md
Labels: server, other

#2069 Allow Code Lenses without a command
  lib/ruby_lsp/requests/support/common.rb
Labels: enhancement, server

#2075 Ignore `test/expectations/` for sorbet
  CONTRIBUTING.md
  sorbet/config
  test/requests/code_action_resolve_expectations_test.rb
  test/requests/code_actions_expectations_test.rb
  test/requests/code_actions_formatting_test.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/document_highlight_expectations_test.rb
  test/requests/document_link_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/folding_ranges_expectations_test.rb
  test/requests/formatting_expectations_test.rb
  test/requests/hover_expectations_test.rb
  test/requests/inlay_hints_expectations_test.rb
  test/requests/selection_ranges_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
  test/requests/support/expectations_test_runner.rb
Labels: chore, server

#2083 Prevent test suite from modifying contributors' Bundler settings
  lib/ruby_indexer/test/configuration_test.rb
  test/setup_bundler_test.rb
Labels: server, other

#2091 Ignore vscode log files
  .gitignore
Labels: chore, vscode

#2056 Feat: Add Extract Method to CodeAction
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/code_actions.rb
  lib/ruby_lsp/server.rb
  test/expectations/code_action_resolve/call_chained.exp.json
  test/expectations/code_action_resolve/call_nested_multiline_args.exp.json
  test/expectations/code_action_resolve/def_extract_variable.exp.json
  test/expectations/code_action_resolve/def_multiline_params.exp.json
  test/expectations/code_action_resolve/extract_method.exp.json
  test/expectations/code_action_resolve/extract_variable_first_statement.exp.json
  test/expectations/code_action_resolve/extraction_with_empty_line_between.exp.json
  test/expectations/code_action_resolve/oneline_block_extraction.exp.json
  test/expectations/code_action_resolve/variable_extract.exp.json
  test/expectations/code_actions/aref_field.exp.json
  test/fixtures/extract_method.rb
  vscode/src/test/suite/client.test.ts
Labels: enhancement, server

#2084 Update addons docs for global state
  ADDONS.md
Labels: chore, server

#2078 Add link to feature list from editors docs
  EDITORS.md
Labels: documentation, server

#2042 Support instance variables for definition, hover, completion and workspace symbols
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/test/instance_variables_test.rb
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/listeners/hover.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/completion_resolve.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  test/requests/completion_resolve_test.rb
  test/requests/completion_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/hover_expectations_test.rb
Labels: enhancement, server

#2094 Improve method extract target location
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/code_actions.rb
  test/expectations/code_action_resolve/extract_method.exp.json
Labels: bugfix, server

#2033 Improve client integration tests
  vscode/src/ruby/chruby.ts
  vscode/src/ruby/rubyInstaller.ts
  vscode/src/test/suite/client.test.ts
Labels: bugfix, vscode

#2026 Mention editor names in the 'other editors' section
  EDITORS.md
  README.md
Labels: documentation, server

#2077 Add RubyMine plugin to docs
  EDITORS.md
Labels: documentation, server

#2024 Add ability to linearize ancestors
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
  lib/ruby_indexer/test/index_test.rb
Labels: enhancement, server

#2028 Support inherited methods in definition, hover and completion
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
  lib/ruby_lsp/listeners/completion.rb
  test/requests/completion_test.rb
  test/requests/definition_expectations_test.rb
  test/requests/hover_expectations_test.rb
Labels: enhancement, server

#2112 Fix broken anchor link in EDITOR doc
  EDITORS.md
Labels: documentation

#2113 Avoid computing ancestors if no ivar is found
  lib/ruby_indexer/lib/ruby_indexer/index.rb
Labels: server, other

#2099 Introduce `NodeContext` for listeners
  ADDONS.md
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/listeners/hover.rb
  lib/ruby_lsp/listeners/signature_help.rb
  lib/ruby_lsp/node_context.rb
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/on_type_formatting.rb
  lib/ruby_lsp/requests/signature_help.rb
  test/ruby_document_test.rb
Labels: breaking-change, server
