Repository Shopify/ruby-lsp, pull requests merged in 2024-10, with the labels that each got.

#2637 Guess types for chained invocations
  lib/ruby_lsp/type_inferrer.rb
  test/type_inferrer_test.rb
Labels: bugfix, server

#2581 Add infrastructure for keyword documentation
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/listeners/hover.rb
  lib/ruby_lsp/requests/completion_resolve.rb
  lib/ruby_lsp/static_docs.rb
  ruby-lsp.gemspec
  static_docs/yield.md
  test/requests/completion_resolve_test.rb
  test/requests/hover_expectations_test.rb
Labels: enhancement, server

#2645 Move `defined?` check out of `process_overload`
  lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb
Labels: chore, server

#2647 Adopt tests to Ruby 3.4
  test/expectations/document_link/source_comment.exp.json
  test/fixtures/source_comment.rb
  test/server_test.rb
  vscode/src/test/suite/client.test.ts
Labels: chore

#2618 Avoid a deprecation warning on Ruby 3.4 with the uri gem
  lib/core_ext/uri.rb
  lib/ruby_lsp/requests/support/source_uri.rb
Labels: server, other

#2601 Allow declaration of project addons
  jekyll/add-ons.markdown
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/test_helper.rb
  test/addon_test.rb
Labels: enhancement, server

#2632 Add find references support for constants
  jekyll/design-and-roadmap.markdown
  jekyll/images/references.gif
  jekyll/index.markdown
  lib/ruby_indexer/lib/ruby_indexer/reference_finder.rb
  lib/ruby_indexer/test/reference_finder_test.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/requests/references.rb
  lib/ruby_lsp/requests/rename.rb
  lib/ruby_lsp/server.rb
  test/requests/references_test.rb
Labels: enhancement, server

#2659 Fix `ruby-lsp-check` raising when server message itself is an error
  exe/ruby-lsp-check
Labels: bugfix, server

#2662 Display add-on version in the displayAddons command
  lib/ruby_lsp/server.rb
  test/server_test.rb
  vscode/src/common.ts
  vscode/src/rubyLsp.ts
Labels: enhancement, vscode, server

#2657 Add support for range formatting with Syntax Tree
  jekyll/images/range_formatting.gif
  jekyll/index.markdown
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/requests/range_formatting.rb
  lib/ruby_lsp/requests/support/formatter.rb
  lib/ruby_lsp/requests/support/rubocop_formatter.rb
  lib/ruby_lsp/requests/support/syntax_tree_formatter.rb
  lib/ruby_lsp/server.rb
  test/requests/formatting_test.rb
  test/requests/range_formatting_test.rb
  test/server_test.rb
Labels: enhancement, server

#2650 Add method support to References request
  lib/ruby_indexer/lib/ruby_indexer/reference_finder.rb
  lib/ruby_indexer/test/reference_finder_test.rb
  lib/ruby_lsp/requests/references.rb
  lib/ruby_lsp/requests/rename.rb
Labels: enhancement, server

#2670 Fix some docs links
  .github/ISSUE_TEMPLATE/feature_template.yml
  jekyll/troubleshooting.markdown
Labels: chore

#2669 Handle multibyte characters in RubyDocument
  lib/ruby_lsp/erb_document.rb
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/references.rb
  lib/ruby_lsp/requests/rename.rb
  lib/ruby_lsp/requests/signature_help.rb
  lib/ruby_lsp/ruby_document.rb
  lib/ruby_lsp/server.rb
  test/requests/code_action_resolve_expectations_test.rb
  test/requests/definition_expectations_test.rb
  test/ruby_document_test.rb
Labels: bugfix, server

#2679 Bump dependencies and their rbis
  Gemfile.lock
  sorbet/rbi/gems/docile@1.4.1.rbi
  sorbet/rbi/gems/logger@1.6.1.rbi
  sorbet/rbi/gems/mocha@2.4.5.rbi
  sorbet/rbi/gems/parser@3.3.5.0.rbi
  sorbet/rbi/gems/rbi@0.2.1.rbi
  sorbet/rbi/gems/rbs@3.6.1.rbi
  sorbet/rbi/gems/reline@0.5.10.rbi
  sorbet/rbi/gems/rubocop-ast@1.32.3.rbi
  sorbet/rbi/gems/rubocop-md@1.2.3.rbi
  sorbet/rbi/gems/rubocop@1.66.1.rbi
  sorbet/rbi/gems/simplecov-html@0.13.1.rbi
  sorbet/rbi/gems/spoom@1.5.0.rbi
  sorbet/rbi/gems/stringio@3.1.1.rbi
  sorbet/rbi/gems/tapioca@0.16.3.rbi
  sorbet/rbi/gems/unicode-display_width@2.6.0.rbi
  sorbet/rbi/gems/yard@0.9.37.rbi
Labels: chore

#2682 Find git root through the git extension API
  vscode/package.json
  vscode/src/rubyLsp.ts
  vscode/src/workspace.ts
Labels: bugfix, vscode

#2693 Prevent the same workspace from being lazily launched more than once
  vscode/src/rubyLsp.ts
Labels: bugfix, vscode

#2699 Index all missing global variable nodes
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/global_variable_test.rb
Labels: enhancement, server

#2703 Fix global variable indexing rebase conflict
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
Labels: chore

#2704 Use code units cache API
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/enhancement.rb
  lib/ruby_indexer/lib/ruby_indexer/location.rb
  lib/ruby_indexer/test/enhancements_test.rb
  lib/ruby_lsp/erb_document.rb
  lib/ruby_lsp/listeners/folding_ranges.rb
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/range_formatting.rb
  lib/ruby_lsp/requests/references.rb
  lib/ruby_lsp/requests/rename.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
  lib/ruby_lsp/requests/signature_help.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/response_builders/semantic_highlighting.rb
  lib/ruby_lsp/ruby_document.rb
  lib/ruby_lsp/type_inferrer.rb
  ruby-lsp.gemspec
  sorbet/rbi/gems/prism@1.2.0.rbi
  test/expectations/semantic_highlighting/multibyte_characters.exp.json
Labels: bugfix, server

#2719 Fix conditional local var highlight
  vscode/grammars/ruby.cson.json
  vscode/src/test/suite/grammars.test.ts
Labels: bugfix, vscode

#2736 Log language server restart reasons
  vscode/src/workspace.ts
Labels: vscode, other

#2737 Remove auto-assign workflow
  .github/workflows/auto_assign.yml
Labels: chore

#2744 Accept keyword splat options for server initialization
  lib/ruby_lsp/base_server.rb
Labels: server, other

#2748 Add notes for contributing to the Ruby LSP Rails add-on
  jekyll/contributing.markdown
Labels: documentation, chore

#2747 Make sure `.ruby-lsp` directory always exists
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: server, other

#2749 Add completion for global variables
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/requests/completion.rb
  test/requests/completion_test.rb
Labels: enhancement, server

#2738 Ensure default gem path is also in document selector
  vscode/src/client.ts
  vscode/src/test/suite/client.test.ts
Labels: bugfix, vscode

#2755 Only retry building composed bundle if there's a custom Gemfile
  lib/ruby_lsp/setup_bundler.rb
Labels: server, other

#2763 Include workspace name in error telemetry
  vscode/src/client.ts
Labels: vscode, other

#2765 Prevent passing version to `bin/bundle`
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
  project-words
  test/integration_test.rb
Labels: bugfix, server

#2767 Report Ruby activation errors to telemetry
  vscode/src/ruby.ts
  vscode/src/test/suite/client.test.ts
  vscode/src/test/suite/debugger.test.ts
  vscode/src/test/suite/ruby.test.ts
  vscode/src/workspace.ts
Labels: vscode, other

#2733 Support module_function in the indexer
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/method_test.rb
Labels: enhancement, server

#2783 Avoid showing private methods for external references
  lib/ruby_lsp/listeners/completion.rb
  test/requests/completion_test.rb
Labels: bugfix, server

#2791 Look for Shadowenv in specific Homebrew path and check for untrusted workspace explicitly
  vscode/src/ruby/shadowenv.ts
  vscode/src/test/suite/ruby/shadowenv.test.ts
Labels: bugfix, vscode

#2796 Fix links in Editors page
  jekyll/editors.markdown
Labels: documentation

#2797 Add some necessary guards for operating with a partial bundle
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/requests/support/rubocop_runner.rb
  lib/ruby_lsp/server.rb
Labels: server, other

#2770 Clarify symbol search explanation for VS Code
  lib/ruby_lsp/requests/document_symbol.rb
Labels: chore

#2774 Use Bundler CLI directly and send errors to telemetry
  exe/ruby-lsp-launcher
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/scripts/compose_bundle.rb
  lib/ruby_lsp/scripts/compose_bundle_windows.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/setup_bundler.rb
  lib/ruby_lsp/utils.rb
  sorbet/rbi/shims/bundler.rbi
  test/integration_test.rb
  test/setup_bundler_test.rb
Labels: enhancement, server

#2801 Print Bundler progress to stderr when invoking CLI directly
  lib/ruby_lsp/setup_bundler.rb
  project-words
  sorbet/rbi/shims/bundler.rbi
  test/setup_bundler_test.rb
Labels: server, other

#2800 Show that server is running on degraded mode
  lib/ruby_lsp/server.rb
  vscode/src/client.ts
  vscode/src/common.ts
  vscode/src/status.ts
  vscode/src/test/suite/status.test.ts
Labels: enhancement, vscode

#2778 Add telemetry for launch failures
  vscode/src/client.ts
Labels: vscode, other
