Repository Shopify/ruby-lsp, pull requests merged in 2024-08, with the labels that each got.

#2398 Disable certain LSP features for .erb files through registration options
  lib/ruby_lsp/requests/code_actions.rb
  lib/ruby_lsp/requests/diagnostics.rb
  lib/ruby_lsp/requests/folding_ranges.rb
  lib/ruby_lsp/requests/formatting.rb
  lib/ruby_lsp/requests/on_type_formatting.rb
  lib/ruby_lsp/server.rb
Labels: bugfix, server

#2405 Require Ruby 3.1 in Gemfile
  Gemfile
  Gemfile.lock
Labels: chore, server

#2406 Update rexml and revert 2405
  Gemfile
  Gemfile.lock
Labels: chore, server

#2413 LazyVim: Expand home directory for easier configuration
  EDITORS.md
Labels: chore, server

#2375 Add kate to editors list
  EDITORS.md
Labels: documentation, server

#2358 Allow for indexing enhancements through included hooks
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/enhancement.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/enhancements_test.rb
Labels: enhancement, server

#2415 Indicate multiple signatures for Hover and Completion Resolve
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_lsp/listeners/hover.rb
  lib/ruby_lsp/requests/completion_resolve.rb
  test/requests/completion_resolve_test.rb
  test/requests/hover_expectations_test.rb
Labels: enhancement, server

#2372 Add switch block refactor
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/code_actions.rb
  test/expectations/code_action_resolve/aref_call_aref_assign.exp.json
  test/expectations/code_action_resolve/nested_block_calls.exp.json
  test/expectations/code_action_resolve/nested_oneline_blocks.exp.json
  test/expectations/code_actions/aref_field.exp.json
  test/fixtures/nested_block_calls.rb
  test/fixtures/nested_oneline_blocks.rb
  test/requests/code_actions_expectations_test.rb
  test/ruby_document_test.rb
Labels: enhancement, server

#2428 Update gem RBIs and annotations
  sorbet/rbi/annotations/.gitattributes
  sorbet/rbi/annotations/minitest.rbi
  sorbet/rbi/annotations/mocha.rbi
  sorbet/rbi/annotations/rainbow.rbi
  sorbet/rbi/gems/logger@1.6.0.rbi
  sorbet/rbi/gems/minitest-reporters@1.6.1.rbi
  sorbet/rbi/gems/mocha@2.3.0.rbi
  sorbet/rbi/gems/rbi@0.1.13.rbi
  sorbet/rbi/gems/rbs@3.5.1.rbi
  sorbet/rbi/gems/rexml@3.3.4.rbi
  sorbet/rbi/gems/rubocop@1.64.1.rbi
  sorbet/rbi/gems/spoom@1.3.0.rbi
  sorbet/rbi/gems/syntax_tree@6.2.0.rbi
  sorbet/rbi/gems/tapioca@0.13.3.rbi
  sorbet/rbi/gems/yard-sorbet@0.8.1.rbi
  sorbet/rbi/gems/yard@0.9.36.rbi
Labels: chore

#2427 Use `toggle` block style for code action instead of switch
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/code_actions.rb
  test/expectations/code_action_resolve/aref_call_aref_assign.exp.json
  test/expectations/code_action_resolve/nested_block_calls.exp.json
  test/expectations/code_action_resolve/nested_oneline_blocks.exp.json
  test/expectations/code_actions/aref_field.exp.json
Labels: server, other

#2430 Avoid requiring json for chruby activation
  vscode/src/ruby/chruby.ts
Labels: bugfix, vscode

#2366 Add Ruby Copilot chat agent with domain driven design command
  vscode/README.md
  vscode/package.json
  vscode/src/chatAgent.ts
  vscode/src/rubyLsp.ts
  vscode/yarn.lock
Labels: enhancement, vscode

#2433 Make configuration part of the index
  exe/ruby-lsp
  exe/ruby-lsp-check
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/ruby_indexer.rb
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_lsp/server.rb
  test/server_test.rb
Labels: server, other

#2432 Bugfix: Recognise ERB files correctly in Neovim
  lib/ruby_lsp/server.rb
Labels: server, other

#2449 Create a new issue template for non-VS Code editor users
  .github/ISSUE_TEMPLATE/bug_template_non_vscode.yml
  .github/ISSUE_TEMPLATE/bug_template_vscode.yml
Labels: chore

#2437 Create RBSDocument
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/internal.rb
  lib/ruby_lsp/rbs_document.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/store.rb
  test/rbs_document_test.rb
Labels: enhancement, server

#2218 Make Rails app detection based on Rails::Application superclass
  lib/ruby_lsp/setup_bundler.rb
  test/fixtures/rails_application.rb
  test/setup_bundler_test.rb
Labels: bugfix, server

#2460 Run signature blocks ahead of time and compact after indexing
  exe/ruby-lsp
  lib/ruby_lsp/server.rb
Labels: server, other

#2470 Avoid compacting GC during tests
  lib/ruby_lsp/server.rb
Labels: chore

#2471 Fix singleton class nesting when inside top level reference
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
Labels: bugfix, server

#2474 Avoid using stubs in test_helper.rb as it depends on Mocha
  lib/ruby_lsp/test_helper.rb
Labels: bugfix, server

#2468 Add literal types to inferrer
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/type_inferrer.rb
  test/requests/completion_test.rb
  test/type_inferrer_test.rb
Labels: enhancement, server

#2477 Mention the `Collect Ruby LSP Information for Issue Reporting` command in the issue template.
  .github/ISSUE_TEMPLATE/bug_template_vscode.yml
Labels: chore

#2478 Support semantic token deltas
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/listeners/inlay_hints.rb
  lib/ruby_lsp/listeners/semantic_highlighting.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/response_builders/semantic_highlighting.rb
  lib/ruby_lsp/server.rb
  test/requests/semantic_highlighting_expectations_test.rb
  test/requests/semantic_tokens_delta_test.rb
  test/requests/support/semantic_token_encoder_test.rb
  test/ruby_document_test.rb
Labels: enhancement, server

#2481 Turn off semantic highlighting on files with more than 100k chars
  lib/ruby_lsp/requests/semantic_highlighting.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/store.rb
  test/server_test.rb
Labels: enhancement, server

#2479 Minimize semantic tokens returned for constants and method calls
  lib/ruby_lsp/listeners/semantic_highlighting.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
  test/expectations/semantic_highlighting/aref_field.exp.json
  test/expectations/semantic_highlighting/aref_variable.exp.json
  test/expectations/semantic_highlighting/block_locals.exp.json
  test/expectations/semantic_highlighting/call_invocation.exp.json
  test/expectations/semantic_highlighting/call_invocation_with_variable_receiver.exp.json
  test/expectations/semantic_highlighting/call_invocation_with_variable_receiver_and_arguments.exp.json
  test/expectations/semantic_highlighting/class_declaration_with_superclass.exp.json
  test/expectations/semantic_highlighting/command_call.exp.json
  test/expectations/semantic_highlighting/const.exp.json
  test/expectations/semantic_highlighting/def_endless.exp.json
  test/expectations/semantic_highlighting/defs.exp.json
  test/expectations/semantic_highlighting/destructured_splat_block_arg.exp.json
  test/expectations/semantic_highlighting/fcall_invocation.exp.json
  test/expectations/semantic_highlighting/fcall_invocation_variable_arguments.exp.json
  test/expectations/semantic_highlighting/field_assignment.exp.json
  test/expectations/semantic_highlighting/implicit_node.exp.json
  test/expectations/semantic_highlighting/lambda_locals.exp.json
  test/expectations/semantic_highlighting/lambdas.exp.json
  test/expectations/semantic_highlighting/local_variables.exp.json
  test/expectations/semantic_highlighting/local_vars_and_params.exp.json
  test/expectations/semantic_highlighting/method_params.exp.json
  test/expectations/semantic_highlighting/module_and_reference.exp.json
  test/expectations/semantic_highlighting/multi_assignment.exp.json
  test/expectations/semantic_highlighting/multibyte_characters.exp.json
  test/expectations/semantic_highlighting/pinned_variable.exp.json
  test/expectations/semantic_highlighting/sclass.exp.json
  test/expectations/semantic_highlighting/shadowed_block_arg.exp.json
  test/expectations/semantic_highlighting/single_line_lambda.exp.json
  test/expectations/semantic_highlighting/special_ruby_methods.exp.json
  test/expectations/semantic_highlighting/var_aref_variable.exp.json
  test/expectations/semantic_highlighting/var_field_variable.exp.json
  test/expectations/semantic_highlighting/vcall_invocation.exp.json
  test/fixtures/call_invocation.rb
  test/fixtures/fcall_invocation.rb
  test/requests/semantic_highlighting_expectations_test.rb
Labels: enhancement, server

#2464 Document initialization options
  EDITORS.md
Labels: documentation

#2499 Protect method resolution from circular aliases
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#2500 Add `entries_for` method to indexer
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: enhancement, server

#2507 Raise AddonNotFoundError exception when the addon is not found
  lib/ruby_lsp/addon.rb
  test/addon_test.rb
Labels: server, other

#2509 Return semantic tokens for local vars shadowed by parameters
  lib/ruby_lsp/listeners/semantic_highlighting.rb
  test/expectations/semantic_highlighting/vars_shadowed_by_params.exp.json
  test/fixtures/vars_shadowed_by_params.rb
Labels: bugfix, server

#2438 Fix Ruby LSP formatting range to comply with LSP specification
  lib/ruby_lsp/requests/formatting.rb
Labels: bugfix, server

#2511 Drop `benchmark` dependency
  exe/ruby-lsp
Labels: chore, server
