Repository Shopify/ruby-lsp, pull requests merged in 2025-03, with the labels that each got.

#3271 Allow add-ons to extend test discovery
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/requests/discover_tests.rb
  test/requests/discover_tests_test.rb
Labels: enhancement, addons, server

#3272 Allowing finding test items based on ID and URI
  vscode/src/test/suite/testController.test.ts
  vscode/src/testController.ts
Labels: vscode, other

#3275 Assorted RBS grammar fixes
  vscode/grammars/rbs.injection.json
  vscode/src/test/suite/grammars.test.ts
Labels: bugfix, vscode, graphite-merge

#3277 Exclude certain Bundler settings when composing bundle
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: bugfix, server

#3280 Add awesome-ruby-lsp reference to docs
  jekyll/index.markdown
Labels: chore

#3289 Ensure `URI.from_path` is available to minitest runner
  lib/ruby_lsp/ruby_lsp_reporter_plugin.rb
  project-words
  test/minitest_test_runner_test.rb
Labels: chore

#3299 Update Slack link in header
  jekyll/_config.yml
Labels: chore

#3309 Hook server and extension test execution
  Gemfile
  lib/ruby_indexer/test/configuration_test.rb
  lib/ruby_lsp/listeners/test_style.rb
  lib/ruby_lsp/ruby_lsp_reporter_plugin.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/test_reporter.rb
  lib/ruby_lsp/test_unit_test_runner.rb
  test/minitest_test_runner_test.rb
  test/test_helper.rb
  test/test_unit_test_runner_test.rb
Labels: enhancement, server, graphite-merge

#3323 Add support for appendOutput to streaming explorer updates
  vscode/src/testController.ts
Labels: enhancement, vscode

#3329 Do not include workspace name as part of relative path
  vscode/src/testController.ts
Labels: bugfix, vscode

#3330 Accumulate streaming promises and await all before exiting
  vscode/src/testController.ts
Labels: bugfix, vscode

#3332 Update Sorbet, remove shim
  Gemfile.lock
  sorbet/config
  sorbet/rbi/shims/test_reporter.rbi
Labels: chore

#3336 Automatically discover children for test files that weren't expanded
  vscode/src/test/suite/testController.test.ts
  vscode/src/testController.ts
Labels: bugfix, vscode

#3338 Allow cancelling test runs
  vscode/src/test/suite/testController.test.ts
  vscode/src/testController.ts
Labels: vscode, other

#3340 Prefix framework tags with `framework:`
  lib/ruby_lsp/listeners/spec_style.rb
  lib/ruby_lsp/listeners/test_style.rb
  lib/ruby_lsp/requests/support/test_item.rb
  test/requests/discover_tests_test.rb
  test/requests/resolve_test_commands_test.rb
  test/response_builders/test_collection_test.rb
Labels: server, other

#3342 Use no-cache option when bundle installing
  lib/ruby_lsp/setup_bundler.rb
  test/integration_test.rb
  test/setup_bundler_test.rb
Labels: bugfix, server

#3339 Handle changing visibility post method definition
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/method_test.rb
Labels: bugfix, server

#3353 Apply debug env customizations on top of Ruby environment
  vscode/src/debugger.ts
  vscode/src/test/suite/debugger.test.ts
Labels: bugfix, vscode

#3355 Troubleshooting silent Ruby LSP output channel docs hint
  jekyll/troubleshooting.markdown
Labels: documentation

#3326 Introduce test file watcher
  vscode/src/testController.ts
Labels: enhancement, vscode

#3335 Expand test directory command resolution with requires
  lib/ruby_lsp/listeners/test_style.rb
  test/requests/resolve_test_commands_test.rb
Labels: bugfix, server

#3364 Upgrade development gems
  Gemfile.lock
  lib/ruby_indexer/test/rbs_indexer_test.rb
  sorbet/rbi/gems/date@3.4.1.rbi
  sorbet/rbi/gems/io-console@0.8.0.rbi
  sorbet/rbi/gems/json@2.10.2.rbi
  sorbet/rbi/gems/logger@1.7.0.rbi
  sorbet/rbi/gems/minitest-reporters@1.7.1.rbi
  sorbet/rbi/gems/minitest@5.25.5.rbi
  sorbet/rbi/gems/mocha@2.7.1.rbi
  sorbet/rbi/gems/pp@0.6.2.rbi
  sorbet/rbi/gems/prettyprint@0.2.0.rbi
  sorbet/rbi/gems/psych@5.2.3.rbi
  sorbet/rbi/gems/racc@1.8.1.rbi
  sorbet/rbi/gems/rake@13.2.1.rbi
  sorbet/rbi/gems/rbi@0.3.1.rbi
  sorbet/rbi/gems/rbs@3.9.1.rbi
  sorbet/rbi/gems/reline@0.6.0.rbi
  sorbet/rbi/gems/rubocop-minitest@0.36.0.rbi
  sorbet/rbi/gems/spoom@1.6.1.rbi
  sorbet/rbi/gems/stringio@3.1.6.rbi
  sorbet/rbi/gems/tapioca@0.16.11.rbi
  sorbet/rbi/gems/yard-sorbet@0.9.0.rbi
  sorbet/rbi/shims/uri.rbi
  test/integration_test.rb
Labels: chore

#3360 Add coverage data collection to the test reporter
  lib/ruby_lsp/test_reporter.rb
  sorbet/rbi/shims/test_reporter.rbi
  test/minitest_test_runner_test.rb
  test/test_helper.rb
  test/test_reporter_test.rb
Labels: enhancement, server
