Repository Shopify/ruby-lsp, pull requests merged in 2025-08, with the labels that each got.

#3689 Allow running tests without a bundle
  lib/ruby_lsp/listeners/test_discovery.rb
  lib/ruby_lsp/listeners/test_style.rb
  test/requests/discover_tests_test.rb
Labels: bugfix, server

#3711 Disable spring when running tests through the explorer
  vscode/src/streamingRunner.ts
Labels: bugfix, vscode

#3716 Prevent Bundler composition tests from printing
  test/setup_bundler_test.rb
Labels: chore

#3715 Account for module wrapping Minitest specs
  lib/ruby_lsp/listeners/spec_style.rb
  test/requests/discover_tests_test.rb
Labels: bugfix, server

#3727 Add a timeout to the test method `pop_response`
  lib/ruby_lsp/base_server.rb
Labels: chore

#3728 Fix markdown syntax for note class
  jekyll/editors.markdown
Labels: documentation
