Repository Shopify/ruby-lsp, pull requests merged in 2025-01, with the labels that each got.

#3003 Upgrade to Ruby 3.4.1
  .github/workflows/ci.yml
  .ruby-version
  Gemfile.lock
  jekyll/Gemfile
  jekyll/Gemfile.lock
  lib/ruby_lsp/listeners/document_symbol.rb
  test/expectations/diagnostics/syntax_diagnostics.exp.json
  test/integration_test.rb
  test/requests/diagnostics_test.rb
  test/ruby_document_test.rb
  vscode/src/test/rubyVersion.ts
  vscode/src/test/suite/client.test.ts
  vscode/src/test/suite/ruby/chruby.test.ts
  vscode/src/test/suite/ruby/rubyInstaller.test.ts
Labels: chore

#3012 Handle missing specs when listing transitive dependencies
  lib/ruby_indexer/lib/ruby_indexer/configuration.rb
  lib/ruby_indexer/test/configuration_test.rb
Labels: bugfix, server

#3014 Fix Bundler default bindir on Windows
  exe/ruby-lsp
  lib/ruby_lsp/setup_bundler.rb
Labels: bugfix, server

#2976 Locate targets under mutex lock
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/erb_document.rb
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/rbs_document.rb
  lib/ruby_lsp/requests/code_action_resolve.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/document_highlight.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/prepare_rename.rb
  lib/ruby_lsp/requests/references.rb
  lib/ruby_lsp/requests/rename.rb
  lib/ruby_lsp/requests/show_syntax_tree.rb
  lib/ruby_lsp/requests/signature_help.rb
  lib/ruby_lsp/ruby_document.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/store.rb
  test/erb_document_test.rb
  test/rbs_document_test.rb
  test/requests/code_action_resolve_expectations_test.rb
  test/requests/code_actions_expectations_test.rb
  test/requests/code_actions_formatting_test.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/diagnostics_test.rb
  test/requests/document_highlight_expectations_test.rb
  test/requests/document_link_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/requests/folding_ranges_expectations_test.rb
  test/requests/formatting_expectations_test.rb
  test/requests/formatting_test.rb
  test/requests/inlay_hints_expectations_test.rb
  test/requests/on_type_formatting_test.rb
  test/requests/prepare_rename_expectations_test.rb
  test/requests/range_formatting_test.rb
  test/requests/references_test.rb
  test/requests/rename_test.rb
  test/requests/selection_ranges_expectations_test.rb
  test/requests/semantic_highlighting_expectations_test.rb
  test/requests/support/expectations_test_runner.rb
  test/ruby_document_test.rb
  test/store_test.rb
  test/type_inferrer_test.rb
Labels: bugfix, server

#2942 Only reindex documents if declarations are being modified
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/ruby_document.rb
  lib/ruby_lsp/server.rb
  test/requests/code_lens_expectations_test.rb
  test/requests/document_symbol_expectations_test.rb
  test/ruby_document_test.rb
  test/server_test.rb
Labels: enhancement, server

#3030 Ensure requests are not assuming the presence of file paths for entries
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/requests/rename.rb
  lib/ruby_lsp/requests/workspace_symbol.rb
  test/requests/definition_expectations_test.rb
  test/requests/rename_test.rb
  test/requests/workspace_symbol_test.rb
Labels: bugfix, server

#3033 Avoid reporting the same Bundler install error twice
  exe/ruby-lsp-launcher
Labels: bugfix, server

#3043 Only load install error instance after requiring Bundler
  exe/ruby-lsp-launcher
Labels: bugfix, server

#3057 Fail build on ESLint warnings
  vscode/package.json
Labels: chore, vscode

#3062 Fix singleton indexing under compact namespaces
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/classes_and_modules_test.rb
Labels: bugfix, server

#3065 Use local executables when working on the Ruby LSP
  vscode/src/ruby.ts
  vscode/src/test/suite/ruby.test.ts
Labels: chore

#3068 Update `GUESSED_TYPES_URL`
  lib/ruby_lsp/utils.rb
Labels: bugfix, server

#3070 Prevent double activation when multiple documents are opened
  vscode/src/rubyLsp.ts
Labels: bugfix, vscode

#3067 Change our internal RuboCop integration identifier
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/server.rb
  test/global_state_test.rb
  test/requests/code_actions_formatting_test.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/diagnostics_test.rb
  test/requests/formatting_expectations_test.rb
  test/server_test.rb
  vscode/package.json
Labels: bugfix, server

#3041 Request diagnostic refresh when RuboCop configs change
  lib/ruby_lsp/client_capabilities.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/utils.rb
  test/server_test.rb
Labels: bugfix, server

#3074 Remove server side document selectors
  lib/ruby_lsp/requests/code_actions.rb
  lib/ruby_lsp/requests/diagnostics.rb
  lib/ruby_lsp/requests/folding_ranges.rb
  lib/ruby_lsp/requests/formatting.rb
  lib/ruby_lsp/requests/on_type_formatting.rb
  lib/ruby_lsp/requests/semantic_highlighting.rb
Labels: bugfix, server

#3086 Update Slack invite link
  README.md
  jekyll/add-ons.markdown
  jekyll/index.markdown
  vscode/README.md
Labels: chore

#3066 Check if bundle is valid before restarting
  exe/ruby-lsp-launcher
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/setup_bundler.rb
  lib/ruby_lsp/utils.rb
  project-words
  test/server_test.rb
  test/setup_bundler_test.rb
  vscode/src/workspace.ts
Labels: enhancement, vscode

#3105 Avoid failing if file is quickly created and deleted
  lib/ruby_lsp/server.rb
  test/server_test.rb
Labels: bugfix, server, graphite-merge

#3109 Allow snippets for Cursor editor
  lib/ruby_lsp/requests/on_type_formatting.rb
  test/requests/on_type_formatting_test.rb
Labels: bugfix, server, graphite-merge

#3113 Clarify limitations of rename
  jekyll/index.markdown
Labels: documentation, chore

#3123 Add jekyll as a VS Code workspace
  lsp.code-workspace
Labels: chore

#3125 Extract `actual_nesting` to Index
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/lib/ruby_indexer/reference_finder.rb
Labels: chore, server
