Repository Shopify/ruby-lsp, pull requests merged in 2025-05, with the labels that each got.

#3443 Point to local executable directly instead of modifying PATH
  vscode/src/client.ts
  vscode/src/ruby.ts
  vscode/src/test/suite/ruby.test.ts
Labels: chore

#3444 Include debug and spawn in the list of promises to await
  vscode/src/streamingRunner.ts
Labels: bugfix, vscode

#3447 Remove T::Enum for SorbetLevel
  lib/ruby_lsp/listeners/completion.rb
  lib/ruby_lsp/listeners/definition.rb
  lib/ruby_lsp/listeners/hover.rb
  lib/ruby_lsp/listeners/signature_help.rb
  lib/ruby_lsp/requests/completion.rb
  lib/ruby_lsp/requests/definition.rb
  lib/ruby_lsp/requests/hover.rb
  lib/ruby_lsp/requests/signature_help.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/ruby_document.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/utils.rb
  test/ruby_document_test.rb
Labels: server, other

#3450 Modify LinkedCancellationSource for asymmetric token cancellation
  vscode/src/linkedCancellationSource.ts
  vscode/src/test/suite/linkendCancellationSource.test.ts
Labels: enhancement, vscode

#3451 Add support for continuous test runs
  vscode/src/testController.ts
Labels: enhancement, vscode

#3449 Hook code lens with the new test discovery
  lib/ruby_lsp/listeners/spec_style.rb
  lib/ruby_lsp/listeners/test_style.rb
  lib/ruby_lsp/requests/code_lens.rb
  lib/ruby_lsp/requests/support/test_item.rb
  lib/ruby_lsp/response_builders/test_collection.rb
  lib/ruby_lsp/server.rb
  vscode/src/client.ts
Labels: enhancement, server

#3458 Log full backtrace on diagnostic and formatting crashes
  lib/ruby_lsp/server.rb
Labels: server, other

#3463 Add refresh support to the test explorer
  vscode/src/test/suite/testController.test.ts
  vscode/src/testController.ts
Labels: enhancement, vscode

#3430 Automatically discover dynamically defined tests
  vscode/src/streamingRunner.ts
  vscode/src/test/suite/testController.test.ts
  vscode/src/testController.ts
Labels: enhancement, vscode

#3344 Improve support for hovering over a gem in Gemfile
  lib/ruby_lsp/listeners/hover.rb
  test/requests/hover_expectations_test.rb
Labels: bugfix, server

#3469 Only load from `cgi` what is required
  lib/ruby_lsp/internal.rb
Labels: server, other

#3462 Ensure store test is empty before resolving in tests
  vscode/src/test/suite/testController.test.ts
Labels: chore

#3472 Exclude non-workspace coverage data
  lib/ruby_lsp/test_reporters/lsp_reporter.rb
  test/test_reporters/lsp_reporter_test.rb
Labels: server, other

#3482 Bring back `extend T::Generic` for add-on API classes
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/response_builders/response_builder.rb
Labels: bugfix, server

#3480 Lazily discover test framework on execution
  vscode/src/test/suite/testController.test.ts
  vscode/src/testController.ts
Labels: vscode, other

#3492 Use a Sinon sandbox for workspace stubs
  vscode/src/test/suite/workspace.test.ts
Labels: chore

#3495 Always reset run object on finalize
  vscode/src/streamingRunner.ts
Labels: bugfix, vscode

#3498 Bump setup-ruby for windows-latest
  .github/workflows/ci.yml
  .github/workflows/dependabot_update_rbis.yml
  .github/workflows/indexing.yml
  .github/workflows/publish_docs.yml
  .github/workflows/version_bump.yml
Labels: chore

#3500 Add `spec` to load path when running Minitest specs
  lib/ruby_lsp/listeners/test_style.rb
  test/requests/resolve_test_commands_test.rb
Labels: bugfix, server

#3510 Bump new explorer rollout to 15%
  vscode/src/common.ts
Labels: vscode, other

#3518 Prevent Minitest reporters from being mutated after LSP hooks
  jekyll/test_explorer.markdown
  lib/ruby_lsp/test_reporters/minitest_reporter.rb
Labels: bugfix, server

#3520 Fix upcoming RBS breaking changes
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/rbs_indexer.rb
  ruby-lsp.gemspec
  test/integration_test.rb
Labels: server, other

#3512 Ignore methods that look like tests inside other namespaces
  lib/ruby_lsp/listeners/test_style.rb
  test/requests/discover_tests_test.rb
Labels: bugfix, server

#3527 Avoid shitfting editor focus when using test code lens
  vscode/src/streamingRunner.ts
  vscode/src/testController.ts
Labels: vscode, other

#3534 Move all abstract methods to RBS syntax
  lib/ruby_indexer/lib/ruby_indexer/enhancement.rb
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_indexer/lib/ruby_indexer/reference_finder.rb
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/listeners/test_discovery.rb
  lib/ruby_lsp/requests/request.rb
  lib/ruby_lsp/requests/support/common.rb
  lib/ruby_lsp/requests/support/formatter.rb
  lib/ruby_lsp/response_builders/response_builder.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/test_helper.rb
  lib/ruby_lsp/utils.rb
Labels: server, other

#3377 find instance variable references with matched scopes
  lib/ruby_indexer/lib/ruby_indexer/reference_finder.rb
  lib/ruby_indexer/test/reference_finder_test.rb
  lib/ruby_lsp/requests/references.rb
Labels: enhancement, server

#3542 Prevent tests from overriding port database
  vscode/src/test/suite/streamingRunner.test.ts
Labels: chore

#3382 Update docs for Zed
  jekyll/editors.markdown
Labels: documentation

#3552 Prevent outdated Bundler errors from crashing launcher
  exe/ruby-lsp-launcher
Labels: bugfix, server

#3546 Update Stray VS Code Workspace Name in Docs
  jekyll/contributing.markdown
Labels: documentation

#3564 chore: remove deprecated activationEvents from extension package.json
  vscode/package.json
Labels: vscode, other
