Repository Shopify/ruby-lsp, pull requests merged in 2025-06, with the labels that each got.

#3544 Index `attr`
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/method_test.rb
Labels: bugfix, server

#3572 Pick most specific parent class during linearization
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#3573 Automatically clear Ruby workspace cache if the path no longer exists
  vscode/src/ruby.ts
  vscode/src/test/suite/helpers.ts
  vscode/src/test/suite/ruby.test.ts
Labels: bugfix, vscode

#3574 Increase the full test discovery rollout to 70%
  vscode/src/common.ts
Labels: vscode, other

#3579 Handle attr with `true` argument for writer
  lib/ruby_indexer/lib/ruby_indexer/declaration_listener.rb
  lib/ruby_indexer/test/method_test.rb
Labels: bugfix, server

#3560 feat: register profile command
  vscode/package.json
  vscode/src/common.ts
  vscode/src/rubyLsp.ts
Labels: enhancement, vscode

#3583 Utf 8 encoding issue
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/server.rb
  test/ruby_document_test.rb
  test/server_test.rb
Labels: bugfix, server

#3582 Register all test discovery listener events in one go
  lib/ruby_lsp/listeners/spec_style.rb
  lib/ruby_lsp/listeners/test_discovery.rb
  lib/ruby_lsp/listeners/test_style.rb
Labels: breaking-change, server

#3589 Increase the full test discovery rollout to 100%
  vscode/src/common.ts
Labels: vscode, other

#3590 Update `collect_references` to use `Prism::LexResult`
  lib/ruby_lsp/requests/references.rb
  test/requests/references_test.rb
Labels: bugfix, server

#3619 Bump build timeout to 40 minutes
  .github/workflows/ci.yml
Labels: chore

#3367 Upgrade RuboCop related gems
  .rubocop.yml
  Gemfile
  Gemfile.lock
  lib/ruby_lsp/requests/support/rubocop_runner.rb
  sorbet/rbi/gems/lint_roller@1.1.0.rbi
  sorbet/rbi/gems/rubocop-minitest@0.38.1.rbi
  sorbet/rbi/gems/rubocop-rake@0.7.1.rbi
  sorbet/rbi/gems/rubocop@1.76.2.rbi
  sorbet/tapioca/require.rb
  test/requests/diagnostics_expectations_test.rb
  test/requests/formatting_expectations_test.rb
Labels: chore

#3622 Upgrade Tapioca
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_lsp/addon.rb
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/requests/request.rb
  lib/ruby_lsp/requests/support/formatter.rb
  lib/ruby_lsp/response_builders/response_builder.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/utils.rb
  sorbet/rbi/gems/ast@2.4.3.rbi
  sorbet/rbi/gems/benchmark@0.4.1.rbi
  sorbet/rbi/gems/date@3.4.1.rbi
  sorbet/rbi/gems/erubi@1.13.1.rbi
  sorbet/rbi/gems/json@2.12.2.rbi
  sorbet/rbi/gems/lint_roller@1.1.0.rbi
  sorbet/rbi/gems/logger@1.7.0.rbi
  sorbet/rbi/gems/minitest@5.25.5.rbi
  sorbet/rbi/gems/mocha@2.7.1.rbi
  sorbet/rbi/gems/netrc@0.11.0.rbi
  sorbet/rbi/gems/parser@3.3.8.0.rbi
  sorbet/rbi/gems/power_assert@2.0.5.rbi
  sorbet/rbi/gems/prism@1.4.0.rbi
  sorbet/rbi/gems/psych@5.2.6.rbi
  sorbet/rbi/gems/racc@1.8.1.rbi
  sorbet/rbi/gems/rainbow@3.1.1.rbi
  sorbet/rbi/gems/rake@13.3.0.rbi
  sorbet/rbi/gems/rbi@0.3.6.rbi
  sorbet/rbi/gems/rbs@4.0.0.dev.4.rbi
  sorbet/rbi/gems/regexp_parser@2.10.0.rbi
  sorbet/rbi/gems/rexml@3.4.1.rbi
  sorbet/rbi/gems/rubocop-ast@1.45.1.rbi
  sorbet/rbi/gems/rubocop-minitest@0.38.1.rbi
  sorbet/rbi/gems/rubocop-rake@0.7.1.rbi
  sorbet/rbi/gems/rubocop-sorbet@0.8.7.rbi
  sorbet/rbi/gems/rubocop@1.76.2.rbi
  sorbet/rbi/gems/ruby-progressbar@1.13.0.rbi
  sorbet/rbi/gems/spoom@1.7.4.rbi
  sorbet/rbi/gems/syntax_tree@6.2.0.rbi
  sorbet/rbi/gems/tapioca@0.17.4.rbi
  sorbet/rbi/gems/test-unit@3.6.8.rbi
  sorbet/rbi/gems/thor@1.3.2.rbi
  sorbet/rbi/gems/yard-sorbet@0.9.0.rbi
  sorbet/rbi/gems/yard@0.9.37.rbi
Labels: server, other

#3613 Move feature configuration to global state
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/listeners/inlay_hints.rb
  lib/ruby_lsp/requests/inlay_hints.rb
  lib/ruby_lsp/server.rb
  lib/ruby_lsp/store.rb
  lib/ruby_lsp/utils.rb
  test/global_state_test.rb
  test/requests/inlay_hints_expectations_test.rb
  test/server_test.rb
Labels: server, other

#3616 Add test add-on command resolution docs
  jekyll/test_framework_addons.markdown
Labels: documentation

#3634 Support Windsurf for setting cursor position in snippets
  lib/ruby_lsp/requests/on_type_formatting.rb
  test/requests/on_type_formatting_test.rb
Labels: enhancement, server

#3632 Allow users to disable test related code lenses
  lib/ruby_lsp/global_state.rb
  lib/ruby_lsp/requests/code_lens.rb
  test/requests/discover_tests_test.rb
  vscode/package.json
Labels: enhancement, vscode, server
