Repository Shopify/ruby-lsp, pull requests merged in 2025-07, with the labels that each got.

#3640 Add documentation for custom test framework reporting
  jekyll/test_framework_addons.markdown
Labels: documentation

#3655 Prevent workspace dependencies from failing if there's no bundle
  lib/ruby_lsp/server.rb
Labels: bugfix, server

#3656 Prevent relative require completion for unsaved files
  lib/ruby_lsp/listeners/completion.rb
  test/requests/completion_test.rb
Labels: bugfix, server

#3650 Upgrade Sorbet and fix visibility violations
  Gemfile.lock
  lib/ruby_indexer/lib/ruby_indexer/entry.rb
  lib/ruby_lsp/base_server.rb
Labels: chore

#3637 Remove excessive mutex synchronization
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/document.rb
  lib/ruby_lsp/server.rb
Labels: server, other

#3662 Avoid sending add-on load error messages in test mode
  lib/ruby_lsp/base_server.rb
  lib/ruby_lsp/server.rb
  test/server_test.rb
Labels: chore

#3654 Filter constant completion suggestions to only include constants
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#3667 Upgrade development gems
  Gemfile.lock
  lib/ruby_indexer/test/configuration_test.rb
  sorbet/rbi/gems/erb@5.0.2.rbi
  sorbet/rbi/gems/io-console@0.8.1.rbi
  sorbet/rbi/gems/json@2.13.0.rbi
  sorbet/rbi/gems/rubocop-ast@1.46.0.rbi
  sorbet/rbi/gems/rubocop@1.78.0.rbi
  sorbet/rbi/gems/syntax_tree@6.3.0.rbi
  sorbet/rbi/gems/tapioca@0.17.7.rbi
  sorbet/rbi/gems/test-unit@3.7.0.rbi
  test/expectations/document_link/source_comment.exp.json
  test/fixtures/source_comment.rb
  vscode/src/test/suite/client.test.ts
Labels: chore

#3669 Avoid requiring add-ons that are copied into the workspace
  lib/ruby_lsp/addon.rb
  test/addon_test.rb
Labels: bugfix, server

#3672 Stop reusing the Prism result for RuboCop for now
  lib/ruby_lsp/requests/support/rubocop_runner.rb
Labels: bugfix, server

#3673 Remove RUBYOPT from ruby-lsp-test-exec
  exe/ruby-lsp-test-exec
  jekyll/test_explorer.markdown
  vscode/src/streamingRunner.ts
Labels: vscode, server, other

#3680 Avoid keeping empty arrays inside constant completion candidates
  lib/ruby_indexer/lib/ruby_indexer/index.rb
  lib/ruby_indexer/test/index_test.rb
Labels: bugfix, server

#3688 Consider extra Minitest spec descriptions
  lib/ruby_lsp/listeners/spec_style.rb
  test/requests/discover_tests_test.rb
Labels: bugfix, server

#3666 Upgrade development Ruby to 3.4.5
  .github/workflows/ci.yml
  .ruby-version
Labels: chore

#3696 Add information on enabling the Ruby LSP using builtin vim.lsp instea…
  jekyll/editors.markdown
Labels: documentation

#3697 Handle `Bundler::Fetcher::NetworkDownError` during Bundler setup
  lib/ruby_lsp/setup_bundler.rb
  test/setup_bundler_test.rb
Labels: server, other
